Repository opennextjs/opennextjs-netlify, pull requests merged in 2020-12, with the labels that each got.

#65 #53 properly test next-on-netlify in onBuild
  .gitignore
  .prettierignore
  index.js
  package-lock.json
  package.json
  sample/.gitignore
  sample/netlify.toml
  sample/package-lock.json
  sample/package.json
  sample/pages/index.js
  sample/pages/server-side.js
  sample/pages/test.js
  sample/plugins/netlify-plugin-nextjs/index.js
  sample/plugins/netlify-plugin-nextjs/manifest.yml
  sample/styles/Home.module.css
  sample/styles/globals.css
  test/index.js
  test/sample/TESTING.md
  test/sample/netlify.toml
  test/sample/next.config.js
  test/sample/pages/_app.js
  test/sample/pages/api/test.js
  test/sample/pages/index.js
Labels: type: chore

#69 Increase test timeout
  package.json
Labels: type: chore

#68 README edits to installation process
  README.md
Labels: type: feature

#70 Update readme logo
  next-on-netlify.png
Labels: type: chore

#72 #67 next export unused script mistakenly failed builds
  .gitignore
  .prettierignore
  helpers/isStaticExportProject.js
  index.js
  test/index.js
Labels: type: bug

#73 Use site's Next.js version
  package-lock.json
  package.json
Labels: type: feature
