Repository opennextjs/opennextjs-netlify, pull requests merged in 2020-11, with the labels that each got.

#19 github tools: fix fossa workflow file
  .github/workflows/fossa.yml
Labels: type: chore

#20 add some initial lightweight testing
  .github/workflows/test.yml
  .prettierignore
  __mocks__/cpx.js
  __mocks__/make-dir.js
  __mocks__/makef.js
  __mocks__/next-on-netlify.js
  index.js
  package-lock.json
  package.json
  sample/.gitignore
  sample/TESTING.md
  sample/netlify.toml
  sample/package-lock.json
  sample/package.json
  sample/pages/_app.js
  sample/pages/api/test.js
  sample/pages/index.js
  sample/pages/test.js
  sample/plugins/netlify-plugin-nextjs/index.js
  sample/plugins/netlify-plugin-nextjs/manifest.yml
  sample/styles/Home.module.css
  sample/styles/globals.css
  test/index.js
Labels: type: chore

#28 Functions UI build settings
  index.js
  test/index.js
Labels: type: bug

#31 Fix deprecated method
  index.js
  package.json
Labels: type: bug

#33 Remove `netlifyConfig` check
  index.js
Labels: type: chore

#32 Run tests on Windows
  .github/workflows/test.yml
Labels: type: feature

#29 Fix `package.json` validation
  index.js
  test/index.js
Labels: type: bug

#34 Use test fixtures
  __mocks__/cpx.js
  __mocks__/make-dir.js
  __mocks__/makef.js
  __mocks__/next-on-netlify.js
  index.js
  package-lock.json
  package.json
  test/fixtures/invalid_next_config/next.config.js
  test/fixtures/publish_copy_files/out_publish/subdir/dummy.txt
  test/fixtures/publish_copy_files/publish/subdir/dummy.txt
  test/fixtures/publish_copy_files/subdir/dummy.txt
  test/index.js
Labels: type: chore

#36 Fix `failBuild()` testing
  index.js
  test/index.js
Labels: type: bug

#37 Improve fixtures setup
  test/index.js
Labels: type: chore

#35 Fix `next.config.js` resolution
  index.js
  package.json
  test/fixtures/deep_invalid_next_config/base/.gitkeep
  test/fixtures/deep_invalid_next_config/next.config.js
  test/index.js
Labels: type: bug

#39 Use the site's Functions directory
  index.js
  package.json
  test/fixtures/functions_copy_files/out_functions/next_random/nextJsPage.js
  test/fixtures/functions_copy_files/out_functions/next_random/next_random.js
  test/index.js
Labels: type: feature

#40 remove legacy functions_src conditional
  index.js
  test/index.js
Labels: type: bug

#41 Make Node.js support precise
  .github/workflows/test.yml
  package.json
Labels: type: chore

#45 Make `next` a peer dependency
  helpers/validateNextUsage.js
  index.js
  package-lock.json
  package.json
Labels: type: feature

#46 Validate Next.js version
  helpers/validateNextUsage.js
  package-lock.json
  package.json
Labels: type: feature

#48 Improve `npm install` fix
  index.js
Labels: type: feature

#49 pass constants FUNCTIONS_SRC and PUBLISH_DIR to nextOnNetlify
  index.js
  package-lock.json
  package.json
  sample/.gitignore
  sample/netlify.toml
  sample/package-lock.json
  sample/package.json
  test/index.js
Labels: type: feature

#51 remove next-aws-lambda install since NoN no longer depends on it
  index.js
Labels: type: chore

#52 fail build if app is using NoN already
  index.js
  test/index.js
Labels: type: feature

#50 update README ahead of UI one-click zero-config install
  README.md
  sample/pages/server-side.js
Labels: type: chore

#57 Fix `require('next')`
  package-lock.json
  package.json
Labels: type: feature

#60 Fix `react` peer dependency
  helpers/validateNextUsage.js
Labels: type: feature

#61 add click to install link to README
  README.md
Labels: type: chore
