Repository opennextjs/opennextjs-netlify, pull requests merged in 2021-11, with the labels that each got.

#762 fix: add missing middleware runtime file
  demo/pages/middle/_middleware.js
  demo/pages/middle/index.js
  package-lock.json
  package.json
  src/helpers/config.js
  test/__snapshots__/index.js.snap
  test/index.js
Labels: type: bug, automerge

#761 fix: don't force rewrite in preview mode
  src/helpers/config.js
  test/__snapshots__/index.js.snap
Labels: type: bug, automerge

#766 chore: move cypress out of demo and fix set up
  cypress/config/all.json
  cypress/config/ci.json
  cypress/fixtures/example.json
  cypress/integration/test.spec.ts
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  cypress/tsconfig.json
  demo/cypress/config/all.json
  demo/netlify.toml
  package.json
Labels: type: chore

#768 fix: use glob to select files to move
  src/helpers/config.js
  src/helpers/files.js
  src/index.js
  test/__snapshots__/index.js.snap
  test/index.js
Labels: type: bug, automerge

#778 fix: switch to globby for static files
  package-lock.json
  package.json
  src/helpers/files.js
  test/index.js
Labels: type: bug, automerge

#767 chore: add docs on rewrites and redirects
  README.md
  docs/redirects-rewrites.md
Labels: documentation, type: chore, automerge

#783 docs: fix link to redirects & rewrites, minor edits
  README.md
  docs/redirects-rewrites.md
Labels: type: chore, automerge

#771 fix: links to docs are pointing to wrong branch
  README.md
Labels: automerge

#795 feat: add docs on middleware
  README.md
  docs/middleware.md
Labels: type: feature

#800 fix: ensure path is encoded
  src/templates/getHandler.js
Labels: type: bug, automerge

#799 chore: update middleware docs wording
  docs/middleware.md
Labels: type: chore, automerge

#796 chore: update issue and pr templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/pull_request_template.md
  .prettierignore
Labels: type: chore, automerge

#789 chore: add e2e
  .eslintrc.js
  cypress/integration/custom-errors.spec.ts
  cypress/integration/default.spec.ts
  cypress/integration/dynamic-routes.spec.ts
  cypress/integration/headers.spec.ts
  cypress/integration/i18n.spec.ts
  cypress/integration/images.spec.ts
  cypress/integration/preview.spec.ts
  cypress/integration/rewrites-redirects.spec.ts
  cypress/integration/trailing-slash.spec.ts
  demo/next.config.js
  demo/pages/index.js
  demo/public/shows1.json
  test/__snapshots__/index.js.snap
Labels: type: chore

#793 fix: use forced catchall for preview mode
  demo/pages/previewTest.js
  src/helpers/config.js
  test/__snapshots__/index.js.snap
Labels: type: bug, automerge

#801 feat: log warning if old functions exist
  package-lock.json
  package.json
  src/helpers/verification.js
  src/index.js
  test/index.js
Labels: type: feature, automerge

#812 feat: don't move files to CDN if they match middleware
  src/helpers/files.js
  test/__snapshots__/index.js.snap
  test/index.js
Labels: type: feature, automerge

#816 feat: move static pages by default
  docs/large-functions.md
  docs/middleware.md
  src/index.js
  test/index.js
Labels: type: feature, automerge

#821 fix: gracefully handle missing middleware
  src/helpers/files.js
  test/index.js
Labels: type: bug, automerge

#826 fix: correct redirect priority and correctly handle ISR pages assets
  demo/pages/api/hello.js
  demo/pages/getStaticProps/withRevalidate/[id].js
  demo/pages/index.js
  src/helpers/config.js
  src/helpers/files.js
  src/templates/getHandler.js
  test/__snapshots__/index.js.snap
  test/index.js
Labels: type: bug, automerge

#834 feat: replace node-fetch with builtin
  src/helpers/functions.js
  src/templates/getHandler.js
  src/templates/handlerUtils.ts
  test/index.js
Labels: type: feature, automerge

#832 fix: don't move files to the CDN if they match redirect/rewrite rules
  demo/next.config.js
  demo/pages/old/image.js
  demo/pages/redirectme.js
  src/helpers/files.js
  test/index.js
Labels: type: bug, automerge

#837 fix: handle missing i18n object
  src/helpers/config.js
Labels: type: bug, automerge

#836 chore: put default demo in demos/default
  .gitignore
  cypress/config/ci.json
  cypress/integration/preview.spec.ts
  demo/local-plugin/index.js
  demos/default/.eslintrc
  demos/default/.gitignore
  demos/default/components/Header.js
  demos/default/local-plugin/index.js
  demos/default/local-plugin/manifest.yml
  demos/default/local-plugin/package-lock.json
  demos/default/local-plugin/package.json
  demos/default/netlify.toml
  demos/default/next.config.js
  demos/default/pages/404.js
  demos/default/pages/500.js
  demos/default/pages/_app.js
  demos/default/pages/api/enterPreview.js
  demos/default/pages/api/exitPreview.js
  demos/default/pages/api/hello-background.js
  demos/default/pages/api/hello.js
  demos/default/pages/api/shows/[...params].js
  demos/default/pages/api/shows/[id].js
  demos/default/pages/deep/import.js
  demos/default/pages/getServerSideProps/[id].js
  demos/default/pages/getServerSideProps/all/[[...slug]].js
  demos/default/pages/getServerSideProps/static.js
  demos/default/pages/getStaticProps/[id].js
  demos/default/pages/getStaticProps/static.js
  demos/default/pages/getStaticProps/with-revalidate.js
  demos/default/pages/getStaticProps/withFallback/[...slug].js
  demos/default/pages/getStaticProps/withFallback/[id].js
  demos/default/pages/getStaticProps/withFallbackBlocking/[id].js
  demos/default/pages/getStaticProps/withRevalidate/[id].js
  demos/default/pages/getStaticProps/withRevalidate/withFallback/[id].js
  demos/default/pages/image.js
  demos/default/pages/index.js
  demos/default/pages/logomark.svg
  demos/default/pages/middle/_middleware.js
  demos/default/pages/middle/index.js
  demos/default/pages/old/image.js
  demos/default/pages/previewTest.js
  demos/default/pages/redirectme.js
  demos/default/pages/shows/[...params].js
  demos/default/pages/shows/[id].js
  demos/default/pages/static.js
  demos/default/pages/static/[id].js
  demos/default/pages/unsplash.jpg
  demos/default/public/next-on-netlify.png
  demos/default/public/shows1.json
  demos/default/styles/Home.module.css
  demos/default/styles/globals.css
  netlify.toml
  package.json
  test/index.js
Labels: type: chore, automerge

#833 feat: add experimental support for TTL
  babel.config.js
  demos/default/pages/getStaticProps/withRevalidate/[id].js
  package-lock.json
  package.json
  src/helpers/config.js
  src/helpers/files.js
  src/index.js
  src/templates/getHandler.js
  src/templates/handlerUtils.ts
  test/index.js
Labels: type: feature, automerge

#842 feat: add support for Next env vars
  demos/default/.env.production
  demos/default/pages/api/hello.js
  demos/default/pages/getServerSideProps/[id].js
  demos/default/pages/getStaticProps/env.js
  package.json
  src/helpers/config.js
  test/__snapshots__/index.js.snap
  test/index.js
Labels: type: feature, automerge
