Repository opennextjs/opennextjs-netlify, pull requests merged in 2021-12, with the labels that each got.

#860 chore: 🚙 type some helper files and constants
  src/constants.ts
  src/helpers/cache.ts
  src/helpers/config.ts
  src/helpers/requiredServerFilesType.ts
Labels: type: chore, automerge

#864 fix: correct handling of data route JSON files
  demos/default/next.config.js
  demos/default/pages/index.js
  src/helpers/files.js
  src/templates/getHandler.js
  test/__snapshots__/index.js.snap
  test/index.js
Labels: type: bug, priority: high, automerge

#874 chore: remove plugin dep
  demos/nx-next-monorepo-demo/package-lock.json
  demos/nx-next-monorepo-demo/package.json
Labels: type: chore, automerge

#873 chore: fix bug report template syntax
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: type: chore, automerge

#875 chore: convert functions helper to TS
  src/constants.ts
  src/helpers/config.ts
  src/helpers/functions.ts
  src/helpers/requiredServerFilesType.ts
Labels: type: chore, automerge

#856 fix: copy public directory output instead of input when using Nx
  cypress/integration/nx/general.spec.ts
  demos/nx-next-monorepo-demo/apps/demo-monorepo/next.config.js
  demos/nx-next-monorepo-demo/apps/demo-monorepo/src/service-worker.ts
  demos/nx-next-monorepo-demo/package-lock.json
  demos/nx-next-monorepo-demo/package.json
  src/helpers/files.js
  src/index.js
Labels: type: bug, automerge

#879 fix: correct root redirect when trailingSlash = false
  src/helpers/redirects.ts
Labels: type: bug, automerge

#878 chore: convert more files to ts
  src/helpers/functions.ts
  src/templates/getHandler.js
  src/templates/getHandler.ts
  src/templates/getPageResolver.js
  src/templates/getPageResolver.ts
  src/templates/handlerUtils.ts
  src/templates/ipx.js
  src/templates/ipx.ts
  tsconfig.json
Labels: type: chore, automerge

#896 chore: add preview mode test link to demo page
  .prettierignore
  demos/default/pages/index.js
Labels: type: chore, automerge

#916 feat: enable TTL for all sites
  src/constants.ts
  src/helpers/files.js
  src/helpers/redirects.ts
  src/templates/getHandler.ts
  test/__snapshots__/index.js.snap
Labels: type: feature, automerge

#918 fix: bypass preview for static files
  src/helpers/redirects.ts
  src/index.js
Labels: type: bug, automerge

#899 chore: add to cypress dashboard for all demo sites
  cypress/config/ci.json
  cypress/config/nx-demo.json
  cypress/config/static-root.json
  demos/default/netlify.toml
  demos/nx-next-monorepo-demo/netlify.toml
  demos/static-root/netlify.toml
  package.json
Labels: type: chore, automerge

#939 chore: convert remaining source files to TypeScript
  package.json
  src/constants.ts
  src/helpers/cache.ts
  src/helpers/files.ts
  src/helpers/verification.ts
  src/index.ts
  src/templates/handlerUtils.ts
Labels: type: chore, automerge

#938 chore: update `release-please` workflow
  .github/workflows/pre-release.yml
  .github/workflows/release-please.yml
Labels: type: chore, automerge

#954 fix: use `rawUrl` for path
  src/templates/getHandler.ts
Labels: type: bug, automerge

#948 fix: handle Windows paths correctly
  src/helpers/cache.ts
  src/helpers/functions.ts
  src/index.ts
  src/templates/getPageResolver.ts
  test/__snapshots__/index.js.snap
  test/index.js
Labels: type: bug, automerge

#955 chore: remove "environment" from release-please workflow
  .github/workflows/pre-release.yml
  .github/workflows/release-please.yml
Labels: type: chore, automerge

#958 chore: fix accept-encoding test
  cypress/integration/static-root/i18n.spec.ts
Labels: type: chore, automerge

#979 chore: revert ignore command
  demos/default/netlify.toml
  demos/nx-next-monorepo-demo/netlify.toml
  demos/static-root/netlify.toml
Labels: type: chore, automerge

#978 fix: warn if publish is "out"
  src/helpers/verification.ts
  test/index.js
Labels: type: bug, automerge

#986 chore: document ISR
  docs/isr.md
Labels: type: chore, automerge

#937 chore: remove beta info
  README.md
  src/helpers/verification.ts
  src/index.ts
Labels: type: chore, automerge

#999 chore: Update bug_report.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: type: chore, automerge

#1010 chore: warn for problematic user rewrites
  src/helpers/redirects.ts
  src/helpers/verification.ts
  src/index.ts
  test/index.js
Labels: type: chore, automerge

#1013 chore: install deps for release-please
  .github/workflows/release-please.yml
Labels: type: chore, automerge

#1012 feat: add support for use with `next export`
  README.md
  demos/next-export/.eslintrc
  demos/next-export/.gitignore
  demos/next-export/README.md
  demos/next-export/local-plugin/index.js
  demos/next-export/local-plugin/manifest.yml
  demos/next-export/local-plugin/package-lock.json
  demos/next-export/local-plugin/package.json
  demos/next-export/netlify.toml
  demos/next-export/next.config.js
  demos/next-export/pages/_app.js
  demos/next-export/pages/another.js
  demos/next-export/pages/index.js
  demos/next-export/public/favicon.ico
  demos/next-export/styles/Home.module.css
  demos/next-export/styles/globals.css
  src/helpers/utils.ts
  src/helpers/verification.ts
  src/index.ts
  test/index.js
Labels: type: feature, automerge

#1020 fix: prevent infinite loop when `/` is ISR
  src/helpers/files.ts
Labels: type: bug, automerge

#1051 fix: fix bug that caused ISR pages to sometimes serve first built version
  src/index.ts
Labels: type: bug, automerge

#1056 fix: force React to use production env
  cypress/integration/default/default.spec.ts
  demos/default/pages/index.js
  src/templates/getHandler.ts
Labels: type: bug, automerge
