Repository opennextjs/opennextjs-netlify, pull requests merged in 2021-05, with the labels that each got.

#264 fix: nextConfig was memoized too early
  index.js
Labels: type: bug

#266 fix: support isDynamicRoute in sls-next >=1.8.0
  src/lib/helpers/isDynamicRoute.js
Labels: type: bug

#270 chore: lock sls-next
  package-lock.json
  package.json
Labels: type: chore

#278 fix: update NoN version to 3.0.0 (isDynamicRoute fix)
  package-lock.json
  package.json
Labels: type: bug

#283 fix(deps): move execa to prod
  .eslintrc.js
  package-lock.json
  package.json
  src/lib/helpers/getSortedRedirects.js
Labels: type: bug

#289 chore: upgrade NoN to 3.0.1
  package-lock.json
  package.json
Labels: type: chore

#294 fix: dynamic imports with webpack 5
  package-lock.json
  package.json
  src/lib/helpers/copyDynamicImportChunks.js
  src/lib/helpers/setupNetlifyFunctionForPage.js
  src/tests/dynamicImports.test.js
Labels: type: bug

#304 Revert "fix: dynamic imports with webpack 5"
  package-lock.json
  package.json
  src/lib/helpers/copyDynamicImportChunks.js
  src/lib/helpers/setupNetlifyFunctionForPage.js
  src/tests/dynamicImports.test.js
Labels: type: chore

#305 fix: handle dynamic import chunks in Webpack 5
  package-lock.json
  package.json
  src/lib/helpers/copyDynamicImportChunks.js
  src/lib/helpers/setupNetlifyFunctionForPage.js
  src/tests/dynamicImports.test.js
Labels: type: bug

#317 fix: refactor image function
  package-lock.json
  package.json
  src/lib/templates/imageFunction.js
Labels: type: bug

#324 chore: update README (build details, caveats)
  README.md
Labels: type: chore

#325 chore: doc included-files in README
  README.md
Labels: type: chore

#328 chore: run CI on latest Node.js
  .github/workflows/test.yml
Labels: type: chore

#330 fix: use allowlist for remote images
  README.md
  index.js
  src/lib/templates/imageFunction.js
Labels: type: bug

#331 docs: update ToC
  README.md
Labels: documentation, type: chore

#332 fix: add sharp optimizations
  src/lib/templates/imageFunction.js
Labels: type: bug

#334 perf: parallelize page setup
  package-lock.json
  package.json
  src/lib/helpers/copyDynamicImportChunks.js
  src/lib/helpers/runJobsQueue.js
  src/lib/pages/api/setup.js
  src/lib/pages/getInitialProps/setup.js
  src/lib/pages/getServerSideProps/setup.js
  src/lib/pages/getStaticProps/setup.js
  src/lib/pages/getStaticPropsWithFallback/setup.js
  src/lib/pages/getStaticPropsWithRevalidate/setup.js
  src/lib/pages/withoutProps/setup.js
  src/lib/pages/worker.js
  src/lib/steps/setupPages.js
Labels: type: feature

#335 fix: catch oversize image response
  src/lib/templates/imageFunction.js
Labels: next/image, type: bug

#344 fix: handle image rotation
  src/lib/templates/imageFunction.js
Labels: type: bug

#343 fix: force serverless target
  helpers/doesNotNeedPlugin.js
  helpers/getNextConfig.js
  helpers/hasCorrectNextConfig.js
  helpers/verifyBuildTarget.js
  index.js
  test/index.js
Labels: type: bug

#355 fix(watch): add missing bin property
  package.json
  src/index.js
  src/next-on-netlify.js
Labels: type: bug

#363 ci: set check_latest to true
  .github/workflows/test.yml
  src/lib/helpers/handleFileTracking.js
Labels: type: chore
