Repository opennextjs/opennextjs-netlify, pull requests merged in 2021-06, with the labels that each got.

#371 chore: move README into docs/
  README.md
  docs/caveats.md
  docs/cli-usage.md
  docs/custom-functions.md
  docs/custom-redirects.md
  docs/faq.md
  docs/image-handling.md
  docs/local-files-in-runtime.md
Labels: type: chore

#375 feat: add etag to image function
  package-lock.json
  package.json
  src/lib/templates/imageFunction.js
Labels: next/image, type: feature

#360 chore: change func template to remove callback
  src/lib/templates/functionBase.js
Labels: type: chore

#374 feat: support for basePath
  src/cypress/fixtures/next.config.js-with-basePath
  src/cypress/fixtures/pages/getServerSideProps/[id].js
  src/cypress/fixtures/pages/getServerSideProps/static.js
  src/cypress/integration/basePath_spec.js
  src/lib/config.js
  src/lib/helpers/convertToBasePathRedirects.js
  src/lib/helpers/formatRedirectTarget.js
  src/lib/pages/withoutProps/redirects.js
  src/lib/steps/setupRedirects.js
  src/tests/__snapshots__/basePath.test.js.snap
  src/tests/basePath.test.js
  src/tests/fixtures/next.config.js-with-basePath.js
Labels: type: feature

#385 fix: basePath is undefined when a site has no config file
  src/lib/helpers/convertToBasePathRedirects.js
  src/lib/helpers/formatRedirectTarget.js
  src/lib/pages/withoutProps/redirects.js
  src/lib/steps/setupRedirects.js
Labels: type: bug

#398 docs: adds context for docs
  docs/caveats.md
  docs/cli-usage.md
  docs/custom-functions.md
  docs/custom-redirects.md
  docs/faq.md
  docs/image-handling.md
  docs/local-files-in-runtime.md
Labels: documentation, type: chore

#401 feat: add demo site
  .netlify/state.json
  demo/.gitignore
  demo/README.md
  demo/components/Header.js
  demo/netlify.toml
  demo/next.config.js
  demo/package.json
  demo/pages/_app.js
  demo/pages/api/hello-background.js
  demo/pages/api/hello.js
  demo/pages/api/shows/[...params].js
  demo/pages/api/shows/[id].js
  demo/pages/deep/import.js
  demo/pages/getServerSideProps/[id].js
  demo/pages/getServerSideProps/all/[[...slug]].js
  demo/pages/getServerSideProps/static.js
  demo/pages/getStaticProps/[id].js
  demo/pages/getStaticProps/static.js
  demo/pages/getStaticProps/with-revalidate.js
  demo/pages/getStaticProps/withFallback/[...slug].js
  demo/pages/getStaticProps/withFallback/[id].js
  demo/pages/getStaticProps/withFallbackBlocking/[id].js
  demo/pages/getStaticProps/withRevalidate/[id].js
  demo/pages/getStaticProps/withRevalidate/withFallback/[id].js
  demo/pages/index.js
  demo/pages/shows/[...params].js
  demo/pages/shows/[id].js
  demo/pages/static.js
  demo/pages/static/[id].js
  demo/public/favicon.ico
  demo/styles/Home.module.css
  demo/styles/globals.css
  index.js
  netlify.toml
Labels: type: feature

#408 fix: force serverless target
  demo/next.config.js
  helpers/doesNotNeedPlugin.js
  helpers/getNextConfig.js
  helpers/hasCorrectNextConfig.js
  helpers/verifyBuildTarget.js
  index.js
  package-lock.json
  test/index.js
Labels: type: bug

#420 chore: update to Next 11
  .eslintrc.js
  .gitignore
  demo/.eslintrc
  demo/next.config.js
  demo/package.json
  demo/pages/index.js
  demo/pages/static.js
  demo/pages/static/[id].js
  package-lock.json
  package.json
  src/cypress/fixtures/pages-with-i18n/index.js
  src/cypress/fixtures/pages-with-i18n/static.js
  src/cypress/fixtures/pages-with-i18n/static/[id].js
  src/cypress/fixtures/pages/index.js
  src/cypress/fixtures/pages/static.js
  src/cypress/fixtures/pages/static/[id].js
  src/lib/steps/copyNextAssets.js
  src/tests/dynamicImports.test.js
  src/tests/fixtures/.eslintrc
  src/tests/fixtures/pages-dynamic-imports/index.js
  src/tests/fixtures/pages/index.js
  src/tests/fixtures/pages/static.js
  src/tests/fixtures/pages/static/[id].js
  src/tests/helpers/buildNextApp.js
  test/sample/.eslintrc
Labels: type: chore

#438 docs: add links from readme to docs pages
  README.md
Labels: type: chore

#410 fix: add details to copyNextAssets error messaging
  src/lib/steps/copyNextAssets.js
Labels: type: bug, type: feature

#441 feat: don't upscale images
  demo/pages/image.js
  demo/pages/unsplash.jpg
  package-lock.json
  package.json
  src/lib/templates/imageFunction.js
Labels: type: feature

#452 chore(deps): ignore fs-extra versions >=10
  renovate.json5
Labels: type: chore

#434 feat: monorepo handling
  .gitignore
  README.md
  demo/netlify.toml
  demo/package.json
  docs/monorepos.md
  helpers/checkNxConfig.js
  helpers/doesNotNeedPlugin.js
  helpers/getNextConfig.js
  helpers/getNextRoot.js
  helpers/resolveNextModule.js
  helpers/validateNextUsage.js
  helpers/verifyBuildTarget.js
  index.js
  netlify.toml
  package-lock.json
  package.json
  src/index.js
  src/lib/helpers/getI18n.js
  src/lib/helpers/getSortedRedirects.js
  src/tests/fixtures/next.config.js-with-function.js
  test/index.js
Labels: monorepo, type: feature

#457 fix: handle empty publish directory
  helpers/checkNxConfig.js
  helpers/getNextRoot.js
  index.js
  src/lib/steps/copyNextAssets.js
Labels: type: bug

#400 feat: show summary build status
  index.js
  test/index.js
Labels: type: feature
