Repository opennextjs/opennextjs-netlify, pull requests merged in 2021-02, with the labels that each got.

#87 Use new default functions directory
  .gitignore
  README.md
  index.js
  test/index.js
Labels: type: feature

#94 update failure points in plugin to do nothing instead
  helpers/doesNotNeedPlugin.js
  helpers/doesSiteUseNextOnNetlify.js
  helpers/hasCorrectNextConfig.js
  helpers/isStaticExportProject.js
  helpers/validateNextUsage.js
  index.js
  test/index.js
Labels: type: chore, type: feature

#96 remove next as peer dependency
  package-lock.json
  package.json
Labels: type: chore

#101 chore: decrease package size
  package.json
Labels: type: chore

#100 update README with info about deploy contexts
  README.md
Labels: type: chore

#99 fail build if plugin cant load next.config.js
  .gitignore
  helpers/doesNotNeedPlugin.js
  helpers/hasCorrectNextConfig.js
  index.js
  test/fixtures/broken_next_config/next.config.js
  test/index.js
Labels: type: feature
