Repository opennextjs/opennextjs-netlify, pull requests merged in 2021-07, with the labels that each got.

#467 fix: use correct protocol for image source
  demo/pages/image.js
  demo/pages/logomark.svg
  src/lib/templates/imageFunction.js
Labels: type: bug

#472 chore: update min Next.js version, and log current
  helpers/validateNextUsage.js
Labels: type: chore

#471 fix: skip plugin if build command is empty
  helpers/doesNotNeedPlugin.js
  index.js
  test/index.js
Labels: type: bug

#479 fix: try to resolve next modules via multiple paths
  .eslintrc.js
  .github/workflows/test.yml
  helpers/getNextConfig.js
  helpers/resolveNextModule.js
  helpers/verifyBuildTarget.js
  package.json
  src/lib/helpers/getSortedRedirects.js
  test/index.js
Labels: type: bug

#487 chore: remove log
  helpers/resolveNextModule.js
Labels: type: chore

#486 Change installation step #2 description
  README.md
Labels: type: chore

#496 fix: handle Storybook and other sites that don't build
  helpers/doesNotNeedPlugin.js
  helpers/isStaticExportProject.js
  helpers/usesBuildCommand.js
  index.js
  test/index.js
Labels: type: bug

#518 feat: add support for using image config from next.config.js
  docs/image-handling.md
  index.js
  src/index.js
  src/lib/steps/setupImageFunction.js
  src/lib/templates/imageFunction.js
  src/tests/defaults.test.js
  src/tests/fixtures/next.config.js
Labels: next/image, type: feature

#505 fix: more robust static site detection
  helpers/usesBuildCommand.js
  package-lock.json
  package.json
  test/fixtures/not-static.json
  test/fixtures/static.json
  test/index.js
Labels: type: bug

#520 fix: use POSIX paths for Windows require()s
  package-lock.json
  package.json
  src/lib/config.js
  src/lib/pages/getStaticProps/redirects.js
  src/lib/pages/getStaticProps/setup.js
  src/lib/pages/getStaticPropsWithFallback/redirects.js
  src/lib/pages/getStaticPropsWithFallback/setup.js
  src/lib/pages/getStaticPropsWithRevalidate/redirects.js
  src/lib/pages/getStaticPropsWithRevalidate/setup.js
  src/tests/defaults.test.js
  src/tests/i18n-ssg-root-index.test.js
  src/tests/i18n.test.js
Labels: type: bug

#525 fix: disable png palette
  src/lib/templates/imageFunction.js
Labels: type: bug

#529 fix: catch more export cases
  helpers/usesBuildCommand.js
  test/fixtures/not-static.json
  test/fixtures/static.json
Labels: type: bug

#490 feat!: switch function bundling to esbuild
  index.js
  package-lock.json
  package.json
  src/lib/config.js
  src/lib/helpers/copyDynamicImportChunks.js
  src/lib/helpers/setupNetlifyFunctionForPage.js
  src/lib/templates/createRequestObject.js
  src/lib/templates/createResponseObject.js
  src/lib/templates/functionBase.js
  src/lib/templates/getHandlerFunction.js
  src/lib/templates/getTemplate.js
  src/lib/templates/imageFunction.js
  src/lib/templates/netlifyFunction.js
  src/lib/templates/netlifyOnDemandBuilder.js
  src/lib/templates/renderNextPage.js
  src/tests/configurableDirs.test.js
  src/tests/defaults.test.js
  src/tests/i18n.test.js
  test/index.js
Labels: type: feature

#538 fix: handle monorepo caching
  .eslintrc.js
  helpers/cacheBuild.js
  index.js
  test/index.js
Labels: type: bug

#547 feat: add NEXT_PLUGIN_FORCE_RUN to skip auto-detection
  README.md
  helpers/doesNotNeedPlugin.js
  helpers/usesBuildCommand.js
  test/index.js
Labels: type: feature

#562 chore: don't use esbuild by default
  src/lib/helpers/setupNetlifyFunctionForPage.js
  src/lib/templates/getTemplate.js
  src/tests/configurableDirs.test.js
  src/tests/defaults.test.js
  src/tests/i18n.test.js
  test/index.js
Labels: type: chore

#565 chore: log warning about isr
  src/lib/pages/getStaticPropsWithRevalidate/pages.js
Labels: type: chore

#566 fix: exit on unhandled promise rejection in build
  index.js
Labels: type: bug
