Repository opennextjs/opennextjs-netlify, pull requests merged in 2021-01, with the labels that each got.

#76 upgrade next-on-netlify to 2.7.1
  package-lock.json
  package.json
Labels: type: chore

#77 upgrade next-on-netlify to 2.7.2
  package-lock.json
  package.json
Labels: type: chore

#83 upgrade NoN to 2.8.2, explain CLI usage workflow in README, add jimp
  README.md
  package-lock.json
  package.json
Labels: type: feature

#86 upgrade next-on-netlify to 2.8.4
  package-lock.json
  package.json
Labels: type: bug, type: chore

#89 docs: add publish directory to netlify.toml
  README.md
Labels: type: bug

#91 chore: support Node 15
  .github/workflows/test.yml
Labels: type: chore

#92 Fix toml formatting in README
  README.md
Labels: type: bug
