Repository opennextjs/opennextjs-netlify, pull requests merged in 2021-03, with the labels that each got.

#105 fix: next 10.0.8 changes loadConfig to be async
  helpers/doesNotNeedPlugin.js
  helpers/hasCorrectNextConfig.js
  index.js
  package-lock.json
  package.json
  src/index.js
  src/lib/config.js
  src/lib/helpers/addDefaultLocaleRedirect.js
  src/lib/helpers/addLocaleRedirects.js
  src/lib/helpers/asyncForEach.js
  src/lib/helpers/copyDynamicImportChunks.js
  src/lib/helpers/getDataRouteForRoute.js
  src/lib/helpers/getI18n.js
  src/lib/helpers/getNextConfig.js
  src/lib/helpers/getNextDistDir.js
  src/lib/helpers/getPagesManifest.js
  src/lib/helpers/getPrerenderManifest.js
  src/lib/helpers/getRoutesManifest.js
  src/lib/helpers/isRouteInPrerenderManifest.js
  src/lib/helpers/isRouteWithDataRoute.js
  src/lib/helpers/isRouteWithFallback.js
  src/lib/helpers/setupNetlifyFunctionForPage.js
  src/lib/helpers/setupStaticFileForPage.js
  src/lib/pages/api/pages.js
  src/lib/pages/api/redirects.js
  src/lib/pages/api/setup.js
  src/lib/pages/getInitialProps/pages.js
  src/lib/pages/getInitialProps/redirects.js
  src/lib/pages/getInitialProps/setup.js
  src/lib/pages/getServerSideProps/pages.js
  src/lib/pages/getServerSideProps/redirects.js
  src/lib/pages/getServerSideProps/setup.js
  src/lib/pages/getStaticProps/pages.js
  src/lib/pages/getStaticProps/redirects.js
  src/lib/pages/getStaticProps/setup.js
  src/lib/pages/getStaticPropsWithFallback/pages.js
  src/lib/pages/getStaticPropsWithFallback/redirects.js
  src/lib/pages/getStaticPropsWithFallback/setup.js
  src/lib/pages/getStaticPropsWithRevalidate/pages.js
  src/lib/pages/getStaticPropsWithRevalidate/redirects.js
  src/lib/pages/getStaticPropsWithRevalidate/setup.js
  src/lib/pages/withoutProps/pages.js
  src/lib/pages/withoutProps/redirects.js
  src/lib/pages/withoutProps/setup.js
  src/lib/steps/copyNextAssets.js
  src/lib/steps/setupPages.js
  src/lib/steps/setupRedirects.js
  src/next-on-netlify.js
  src/tests/__snapshots__/i18n.test.js.snap
  src/tests/helpers/buildNextApp.js
  test/index.js
Labels: type: bug

#108 chore: update setup-node github action
  .github/workflows/test.yml
Labels: type: chore

#109 fix: don't publish test files
  package.json
Labels: type: bug

#114 chore: separate `getNextConfig()`
  helpers/getNextConfig.js
  helpers/hasCorrectNextConfig.js
Labels: type: chore

#112 chore: upgrade lock file
  package-lock.json
Labels: type: chore

#113 chore: add Renovate
  renovate.json5
Labels: type: chore

#122 fix: fix missing `await` keyword
  src/lib/pages/getStaticProps/setup.js
Labels: type: bug

#123 fix: fix dynamic `require()` of `next`
  helpers/validateNextUsage.js
  src/lib/helpers/getSortedRedirects.js
Labels: type: bug

#124 fix: fix errors while loading `next.config.js`
  helpers/doesNotNeedPlugin.js
  helpers/getNextConfig.js
  index.js
  src/lib/helpers/getI18n.js
  src/lib/helpers/getNextConfig.js
  src/lib/helpers/getNextDistDir.js
  src/lib/helpers/getPrerenderManifest.js
Labels: type: bug

#127 fix: fix `find-cache-dir` missing dependency
  package-lock.json
  package.json
Labels: type: bug

#128 fix: fix memoization
  helpers/getNextConfig.js
  package-lock.json
  package.json
Labels: type: bug

#143 fix: fix minimum Next.js version
  helpers/validateNextUsage.js
Labels: type: bug

#148 chore: update changelog
  CHANGELOG.md
Labels: type: chore

#159 feat: backport more improvements for Next 9 users
  .gitignore
  README.md
  index.js
  package-lock.json
  package.json
  test/index.js
Labels: type: feature

#110 chore: add release please
  .github/workflows/release-please.yml
  CONTRIBUTING.md
  commitlint.config.js
  package.json
Labels: type: chore

#163 chore: add pr labeler
  .github/workflows/labeler.yml
Labels: type: chore

#167 chore: update README with note about version compatibility
  README.md
Labels: type: chore
