Repository opennextjs/opennextjs-netlify, pull requests merged in 2021-08, with the labels that each got.

#564 fix: preview mode for odb/fallback pages
  src/lib/config.js
  src/lib/helpers/convertToBasePathRedirects.js
  src/lib/helpers/getPreviewModeFunctionName.js
  src/lib/helpers/isRouteWithFallback.js
  src/lib/helpers/setupNetlifyFunctionForPage.js
  src/lib/pages/getStaticProps/pages.js
  src/lib/pages/getStaticProps/redirects.js
  src/lib/pages/getStaticPropsWithFallback/redirects.js
  src/lib/pages/getStaticPropsWithFallback/setup.js
  src/lib/templates/getTemplate.js
  src/tests/__snapshots__/basePath.test.js.snap
  src/tests/__snapshots__/defaults.test.js.snap
  src/tests/__snapshots__/i18n.test.js.snap
  src/tests/defaults.test.js
Labels: type: bug

#579 chore: manually install fossa
  .github/workflows/fossa.yml
Labels: type: chore

#549 feat: use internal functions dir
  index.js
  package-lock.json
  package.json
  test/index.js
Labels: type: feature

#606 feat: try to generate stable build ids
  .gitignore
  demo/next.config.js
  helpers/verifyBuildTarget.js
  index.js
Labels: type: feature

#618 chore: update node version in tests
  .github/workflows/test.yml
Labels: type: chore

#616 fix: move locale/404 to publishPath/404 if custom 404
  src/lib/pages/getStaticProps/setup.js
  src/tests/__snapshots__/basePath.test.js.snap
  src/tests/__snapshots__/defaults.test.js.snap
  src/tests/__snapshots__/i18n.test.js.snap
  src/tests/fixtures/pages/404.js
  src/tests/i18n.test.js
Labels: type: bug
