Repository opennextjs/opennextjs-netlify, pull requests merged in 2022-03, with the labels that each got.

#1260 ci: split canary tests from latest
  .github/workflows/test.yml
Labels: type: chore, automerge

#1263 chore: Add details to cypress and remove extra matrix
  .github/workflows/cypress-demo-nx.yml
  .github/workflows/cypress-demo-static.yml
  .github/workflows/cypress-demo.yml
Labels: type: chore, automerge

#1273 ci: sort snapshots
  package-lock.json
  test/__snapshots__/index.js.snap
  test/index.js
Labels: type: chore, automerge

#1264 fix: use correct publishDir when building from CLI with cwd option
  src/helpers/functions.ts
  src/helpers/verification.ts
Labels: type: bug, automerge

#1259 fix: add next.js 12's new /trace endpoint to HIDDEN_PATHS
  src/constants.ts
  test/__snapshots__/index.js.snap
Labels: automerge

#1277 feat: allow skipping of middleware handling
  src/helpers/files.ts
  src/templates/getHandler.ts
Labels: type: feature, automerge

#1281 fix: correctly find site root when using SSR with Nx
  demos/nx-next-monorepo-demo/apps/demo-monorepo/pages/api/index.js
  src/templates/getHandler.ts
Labels: type: bug, automerge
