Repository opennextjs/opennextjs-netlify, pull requests merged in 2022-01, with the labels that each got.

#1105 fix: add specific rewrites for all SSR routes
  .eslintrc.js
  demos/default/local-plugin/package-lock.json
  demos/default/next.config.js
  package-lock.json
  src/helpers/config.ts
  src/helpers/files.ts
  src/helpers/redirects.ts
  src/helpers/types.ts
  src/helpers/utils.ts
  src/index.ts
  src/templates/getHandler.ts
  test/__snapshots__/index.js.snap
  test/index.js
Labels: type: bug, automerge

#1120 fix: handle `routes-manifest`s without `staticRoutes` defined
  src/helpers/redirects.ts
  src/helpers/types.ts
  test/index.js
Labels: type: bug, automerge

#1127 feat: add request logging
  README.md
  src/templates/getHandler.ts
Labels: type: feature, automerge

#1133 chore: add prose css
  demos/default/components/Header.js
  demos/default/pages/_app.js
  demos/default/pages/index.js
  demos/default/styles/globals.css
Labels: type: chore, automerge

#1137 chore: fix test
  cypress/integration/default/default.spec.ts
Labels: type: chore, automerge

#1130 chore: add more docs
  README.md
  docs/redirects-rewrites.md
Labels: type: chore, automerge

#1126 chore: fix Husky
  package-lock.json
  package.json
Labels: type: chore, automerge

#1149 fix: provide hostname and port to server
  cypress/integration/default/preview.spec.ts
  package-lock.json
  package.json
  src/helpers/functions.ts
  src/templates/getHandler.ts
  src/templates/handlerUtils.ts
Labels: type: bug, automerge

#1078 chore: warn for incorrect _redirects file
  docs/release-notes/v4.md
  src/helpers/verification.ts
  src/index.ts
Labels: type: chore, automerge
