Repository opennextjs/opennextjs-netlify, pull requests merged in 2022-08, with the labels that each got.

#1500 fix: replace netlify:edge identifier with full URL
  plugin/src/templates/edge/ipx.ts
  plugin/src/templates/edge/runtime.ts
  plugin/src/templates/edge/utils.ts
Labels: type: bug

#1503 fix: allow proxy of /_next/static
  plugin/src/templates/edge/runtime.ts
Labels: type: bug

#1518 chore: move plugin package into `packages/*` directory
  .eslintignore
  .gitignore
  .prettierignore
  .release-please-manifest.json
  .vscode/settings.json
  demos/nx-next-monorepo-demo/local-plugin/index.js
  demos/plugin-wrapper/index.js
  package-lock.json
  package.json
  packages/runtime/CHANGELOG.md
  packages/runtime/manifest.yml
  packages/runtime/package.json
  packages/runtime/src/constants.ts
  packages/runtime/src/helpers/cache.ts
  packages/runtime/src/helpers/config.ts
  packages/runtime/src/helpers/edge.ts
  packages/runtime/src/helpers/files.ts
  packages/runtime/src/helpers/functions.ts
  packages/runtime/src/helpers/redirects.ts
  packages/runtime/src/helpers/types.ts
  packages/runtime/src/helpers/utils.ts
  packages/runtime/src/helpers/verification.ts
  packages/runtime/src/index.ts
  packages/runtime/src/middleware/html-rewriter.ts
  packages/runtime/src/middleware/index.ts
  packages/runtime/src/middleware/request.ts
  packages/runtime/src/middleware/response.ts
  packages/runtime/src/templates/edge/bundle.js
  packages/runtime/src/templates/edge/ipx.ts
  packages/runtime/src/templates/edge/runtime.ts
  packages/runtime/src/templates/edge/utils.ts
  packages/runtime/src/templates/getHandler.ts
  packages/runtime/src/templates/getPageResolver.ts
  packages/runtime/src/templates/handlerUtils.ts
  packages/runtime/src/templates/ipx.ts
  packages/runtime/tsconfig.json
  release-please-config.json
  test/helpers/verification.spec.ts
  test/index.js
Labels: type: chore, automerge

#1515 feat: support custom response headers on images served via IPX
  README.md
  demos/default/netlify.toml
  packages/runtime/package.json
  packages/runtime/src/helpers/functions.ts
  packages/runtime/src/helpers/utils.ts
  packages/runtime/src/index.ts
  packages/runtime/src/templates/ipx.ts
  test/helpers/utils.spec.ts
  test/index.js
Labels: type: feature, automerge

#1524 ci: fix release-please
  .release-please-manifest.json
  release-please-config.json
Labels: automerge

#1527 chore: rename repo in package.json
  demos/base-path/local-plugin/package.json
  demos/base-path/package.json
  demos/custom-routes/package.json
  demos/default/package.json
  demos/next-auth/package.json
  demos/next-export/package.json
  demos/nx-next-monorepo-demo/local-plugin/package.json
  demos/plugin-wrapper/package.json
  demos/static-root/local-plugin/package.json
  demos/static-root/package.json
  package.json
  packages/next/package.json
  packages/runtime/package.json
Labels: type: chore, automerge

#1533 chore: retain patched server files
  packages/runtime/src/helpers/files.ts
  packages/runtime/src/index.ts
Labels: type: chore, automerge

#1536 feat: skip run if @netlify/plugin-nextjs installed
  packages/runtime/src/helpers/utils.ts
  packages/runtime/src/index.ts
  test/index.js
Labels: type: feature, automerge

#1540 feat: ✨ change over to next-runtime
  demos/base-path/local-plugin/manifest.yml
  demos/base-path/package.json
  demos/custom-routes/package.json
  demos/default/package.json
  demos/middleware/package.json
  demos/next-auth/package-lock.json
  demos/next-auth/package.json
  demos/next-export/package.json
  demos/nx-next-monorepo-demo/local-plugin/manifest.yml
  demos/plugin-wrapper/package.json
  demos/server-components/package.json
  demos/static-root/local-plugin/manifest.yml
  demos/static-root/package.json
  package-lock.json
  package.json
  packages/runtime/manifest.yml
  packages/runtime/package.json
  packages/runtime/src/helpers/utils.ts
Labels: type: feature, automerge

#1537 chore: removing mentions of plugin
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/cypress-canary.yml
  .github/workflows/cypress-demo-nx.yml
  .github/workflows/cypress-demo-static.yml
  .github/workflows/cypress-demo.yml
  .github/workflows/cypress-middleware.yml
  .github/workflows/test.yml
  .vscode/feat-test.code-snippets
  README.md
  demos/canary/pages/index.js
  demos/default/pages/broken-image.tsx
  demos/default/pages/image.js
  demos/next-export/README.md
  demos/nx-next-monorepo-demo/README.md
  docs/isr.md
  docs/middleware.md
  docs/redirects-rewrites.md
  docs/release-notes/v4.md
  packages/runtime/src/helpers/cache.ts
  packages/runtime/src/helpers/verification.ts
  packages/runtime/src/index.ts
  test/index.js
Labels: type: chore, automerge

#1548 chore: revert skipping runtime, revert package name to plugin-nextjs
  package-lock.json
  packages/runtime/package.json
  packages/runtime/src/helpers/utils.ts
  packages/runtime/src/index.ts
  test/index.js
Labels: type: chore, type: feature, automerge

#1551 chore: fix broken next-auth demo
  .github/workflows/pre-release.yml
  .github/workflows/release-please.yml
  .github/workflows/test.yml
  demos/next-auth/package.json
  demos/next-auth/pages/_app.tsx
  demos/next-auth/tsconfig.json
  package-lock.json
Labels: type: chore, automerge

#1550 chore: revert runtime dep name in demos
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  demos/base-path/local-plugin/manifest.yml
  demos/base-path/package.json
  demos/custom-routes/package.json
  demos/default/package.json
  demos/middleware/package.json
  demos/next-export/package.json
  demos/nx-next-monorepo-demo/local-plugin/manifest.yml
  demos/plugin-wrapper/package.json
  demos/server-components/package.json
  demos/static-root/local-plugin/manifest.yml
  demos/static-root/package.json
  package-lock.json
Labels: type: chore, automerge

#1547 feat: default edge middleware to on
  demos/middleware/netlify.toml
  demos/server-components/netlify.toml
  packages/runtime/src/helpers/edge.ts
  packages/runtime/src/helpers/files.ts
  packages/runtime/src/index.ts
Labels: type: feature, automerge

#1546 feat: add edge middleware support to `ntl dev`
  .vscode/settings.json
  demos/middleware/middleware.ts
  demos/middleware/netlify.toml
  demos/middleware/package.json
  demos/middleware/pages/index.js
  package-lock.json
  packages/next/src/middleware/request.ts
  packages/runtime/package.json
  packages/runtime/src/helpers/dev.ts
  packages/runtime/src/helpers/edge.ts
  packages/runtime/src/helpers/files.ts
  packages/runtime/src/index.ts
  packages/runtime/src/templates/edge/next-dev.ts
  packages/runtime/src/templates/edge/runtime.ts
  packages/runtime/src/templates/edge/utils.ts
  test/index.js
Labels: type: feature, automerge

#1556 fix: use individual next/server deno imports
  packages/runtime/src/templates/edge/next-dev.js
Labels: type: bug, automerge

#1554 chore: Update readme
  README.md
  package-lock.json
Labels: type: chore, automerge

#1559 fix: check for middleware manifest before providing to Object.keys
  packages/runtime/src/index.ts
Labels: type: bug, automerge

#1558 fix: ensure newly-created middleware works
  packages/runtime/src/helpers/dev.ts
  packages/runtime/src/templates/edge/next-dev.js
Labels: type: bug, automerge

#1563 chore: release next-v1.0.0
  .release-please-manifest.json
  package-lock.json
  packages/next/package.json
Labels: type: chore, automerge

#1570 feat: allows disabling function size check
  packages/runtime/src/helpers/utils.ts
  packages/runtime/src/helpers/verification.ts
  test/helpers/verification.spec.ts
Labels: type: feature, automerge

#1575 feat: improve messaging on middleware detection
  packages/runtime/src/helpers/dev.ts
Labels: type: feature, automerge

#1582 feat: only run next-dev middleware in dev
  packages/runtime/src/templates/edge/next-dev.js
Labels: type: feature, automerge

#1584 fix: remove Next.js as a peer dependency
  package-lock.json
  packages/next/CHANGELOG.md
  packages/runtime/package.json
Labels: type: bug, automerge

#1581 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: type: security
