Repository opennextjs/opennextjs-netlify, pull requests merged in 2022-09, with the labels that each got.

#1592 fix: watch for creation of middleware
  .github/workflows/codeql-analysis.yml
  .prettierignore
  package-lock.json
  packages/runtime/package.json
  packages/runtime/src/helpers/dev.ts
Labels: type: bug, automerge

#1588 fix: clean up edge functions during build
  packages/runtime/src/helpers/edge.ts
  packages/runtime/src/index.ts
Labels: type: bug, automerge

#1594 chore: update READMEs
  README.md
  packages/next/README.md
  packages/runtime/README.md
Labels: type: chore, automerge

#1586 feat: create edge function demo
  demos/next-with-edge-functions/.gitignore
  demos/next-with-edge-functions/netlify.toml
  demos/next-with-edge-functions/netlify/edge-functions/helloOnTheEdge.ts
  demos/next-with-edge-functions/next.config.js
  demos/next-with-edge-functions/package.json
  demos/next-with-edge-functions/pages/index.js
  package-lock.json
  package.json
  packages/next/CHANGELOG.md
Labels: type: feature, automerge

#1587 chore(deps): upgrade dependencies in NX demo
  demos/nx-next-monorepo-demo/apps/demo-monorepo/next-env.d.ts
  demos/nx-next-monorepo-demo/apps/demo-monorepo/tsconfig.json
  demos/nx-next-monorepo-demo/local-plugin/package-lock.json
  demos/nx-next-monorepo-demo/package-lock.json
  demos/nx-next-monorepo-demo/package.json
Labels: type: chore, automerge

#1599 chore: update README image with new Next.js logo
  README.md
  next-js-runtime.png
  next-on-netlify.png
Labels: type: chore, automerge

#1597 fix: handle stricter Next type
  packages/runtime/src/helpers/types.ts
Labels: type: bug, automerge

#1589 chore: add Turborepo demo
  demos/turborepo-next-monorepo-demo/apps/docs/.eslintrc.js
  demos/turborepo-next-monorepo-demo/apps/docs/README.md
  demos/turborepo-next-monorepo-demo/apps/docs/next-env.d.ts
  demos/turborepo-next-monorepo-demo/apps/docs/next.config.js
  demos/turborepo-next-monorepo-demo/apps/docs/package.json
  demos/turborepo-next-monorepo-demo/apps/docs/pages/index.tsx
  demos/turborepo-next-monorepo-demo/apps/docs/tsconfig.json
  demos/turborepo-next-monorepo-demo/apps/web/.eslintrc.js
  demos/turborepo-next-monorepo-demo/apps/web/README.md
  demos/turborepo-next-monorepo-demo/apps/web/next-env.d.ts
  demos/turborepo-next-monorepo-demo/apps/web/next.config.js
  demos/turborepo-next-monorepo-demo/apps/web/package.json
  demos/turborepo-next-monorepo-demo/apps/web/pages/api/edge.js
  demos/turborepo-next-monorepo-demo/apps/web/pages/api/index.js
  demos/turborepo-next-monorepo-demo/apps/web/pages/index.tsx
  demos/turborepo-next-monorepo-demo/apps/web/tsconfig.json
  demos/turborepo-next-monorepo-demo/netlify.toml
  demos/turborepo-next-monorepo-demo/netlify/edge-functions/edge.ts
  demos/turborepo-next-monorepo-demo/package-lock.json
  demos/turborepo-next-monorepo-demo/package.json
  demos/turborepo-next-monorepo-demo/packages/eslint-config-custom/index.js
  demos/turborepo-next-monorepo-demo/packages/eslint-config-custom/package.json
  demos/turborepo-next-monorepo-demo/packages/local-plugin/index.js
  demos/turborepo-next-monorepo-demo/packages/local-plugin/manifest.yml
  demos/turborepo-next-monorepo-demo/packages/local-plugin/package-lock.json
  demos/turborepo-next-monorepo-demo/packages/local-plugin/package.json
  demos/turborepo-next-monorepo-demo/packages/tsconfig/README.md
  demos/turborepo-next-monorepo-demo/packages/tsconfig/base.json
  demos/turborepo-next-monorepo-demo/packages/tsconfig/nextjs.json
  demos/turborepo-next-monorepo-demo/packages/tsconfig/package.json
  demos/turborepo-next-monorepo-demo/packages/tsconfig/react-library.json
  demos/turborepo-next-monorepo-demo/packages/ui/Button.tsx
  demos/turborepo-next-monorepo-demo/packages/ui/index.tsx
  demos/turborepo-next-monorepo-demo/packages/ui/package.json
  demos/turborepo-next-monorepo-demo/packages/ui/tsconfig.json
  demos/turborepo-next-monorepo-demo/turbo.json
Labels: type: chore, automerge

#1604 ci: use fossa action
  .github/workflows/fossa.yml
Labels: type: chore, automerge

#1607 feat: support updated remotePatterns configuration
  demos/canary/next.config.js
  demos/canary/package-lock.json
  demos/canary/package.json
  packages/runtime/src/helpers/utils.ts
  packages/runtime/src/index.ts
  test/helpers/utils.spec.ts
Labels: type: feature, automerge

#1612 feat: add support for Next 12.3 middleware matchers
  .eslintignore
  .vscode/settings.json
  cypress/integration/middleware/standard.spec.ts
  demos/base-path/package.json
  demos/canary/middleware.ts
  demos/canary/package-lock.json
  demos/canary/package.json
  demos/custom-routes/package.json
  demos/default/package.json
  demos/middleware/middleware.ts
  demos/middleware/package.json
  demos/middleware/pages/conditional.js
  demos/middleware/tsconfig.json
  demos/next-auth/package.json
  demos/next-export/package.json
  demos/next-i18next/package-lock.json
  demos/next-i18next/package.json
  demos/server-components/package.json
  demos/static-root/package.json
  package-lock.json
  package.json
  packages/next/package.json
  packages/runtime/package.json
  packages/runtime/src/helpers/edge.ts
  packages/runtime/src/helpers/utils.ts
  packages/runtime/src/templates/edge-shared/next-utils.ts
  packages/runtime/src/templates/edge-shared/utils.ts
  packages/runtime/src/templates/edge/matchers.json
  packages/runtime/src/templates/edge/next-dev.js
  packages/runtime/src/templates/edge/runtime.ts
  packages/runtime/tsconfig.json
Labels: type: feature, automerge

#1541 fix: support non-prerendered dynamic routes with fallback false
  cypress/integration/default/dynamic-routes.spec.ts
  packages/runtime/src/helpers/files.ts
  packages/runtime/src/helpers/redirects.ts
  packages/runtime/src/helpers/utils.ts
  packages/runtime/src/templates/getHandler.ts
  test/__snapshots__/index.js.snap
  test/index.js
Labels: type: bug, automerge

#1616 fix: correct handling of edge dev utils
  packages/runtime/src/helpers/edge.ts
Labels: type: bug, automerge

#1613 fix: respect variable set in Netlify config for NEXTAUTH_URL
  packages/runtime/src/index.ts
  test/index.js
Labels: type: bug, automerge

#1635 chore: fix RSC demo
  demos/server-components/components/comment.js
  demos/server-components/components/meta.js
  demos/server-components/package.json
  demos/server-components/pages/csr.js
  demos/server-components/pages/item.server.js
  demos/server-components/pages/rsc.server.js
  demos/server-components/pages/slow.server.js
  package-lock.json
Labels: type: chore, automerge

#1603 fix: check NEXT_DISABLE_NETLIFY_EDGE value rather than if truthy
  README.md
  docs/middleware.md
  docs/release-notes/v4.md
  packages/runtime/src/helpers/edge.ts
  packages/runtime/src/helpers/files.ts
  packages/runtime/src/index.ts
Labels: type: bug, automerge

#1636 chore: fix the nx demo
  cypress/integration/nx/general.spec.ts
  demos/nx-next-monorepo-demo/.gitignore
  demos/nx-next-monorepo-demo/.npmrc
  demos/nx-next-monorepo-demo/.vscode/extensions.json
  demos/nx-next-monorepo-demo/README.md
  demos/nx-next-monorepo-demo/apps/demo-monorepo-e2e/project.json
  demos/nx-next-monorepo-demo/apps/demo-monorepo-e2e/src/integration/app.spec.ts
  demos/nx-next-monorepo-demo/apps/demo-monorepo-e2e/src/support/index.ts
  demos/nx-next-monorepo-demo/apps/demo-monorepo/.eslintrc.json
  demos/nx-next-monorepo-demo/apps/demo-monorepo/jest.config.ts
  demos/nx-next-monorepo-demo/apps/demo-monorepo/next.config.js
  demos/nx-next-monorepo-demo/apps/demo-monorepo/pages/_app.tsx
  demos/nx-next-monorepo-demo/apps/demo-monorepo/pages/api/index.js
  demos/nx-next-monorepo-demo/apps/demo-monorepo/pages/index.tsx
  demos/nx-next-monorepo-demo/apps/demo-monorepo/pages/styles.css
  demos/nx-next-monorepo-demo/apps/demo-monorepo/project.json
  demos/nx-next-monorepo-demo/apps/demo-monorepo/public/nx-logo-white.svg
  demos/nx-next-monorepo-demo/apps/demo-monorepo/public/star.svg
  demos/nx-next-monorepo-demo/apps/demo-monorepo/src/service-worker.ts
  demos/nx-next-monorepo-demo/apps/demo-monorepo/tsconfig.json
  demos/nx-next-monorepo-demo/apps/demo-monorepo/tsconfig.spec.json
  demos/nx-next-monorepo-demo/jest.config.js
  demos/nx-next-monorepo-demo/jest.config.ts
  demos/nx-next-monorepo-demo/jest.preset.js
  demos/nx-next-monorepo-demo/local-plugin/index.js
  demos/nx-next-monorepo-demo/local-plugin/manifest.yml
  demos/nx-next-monorepo-demo/local-plugin/package-lock.json
  demos/nx-next-monorepo-demo/local-plugin/package.json
  demos/nx-next-monorepo-demo/netlify.toml
  demos/nx-next-monorepo-demo/nx.json
  demos/nx-next-monorepo-demo/package-lock.json
  demos/nx-next-monorepo-demo/package.json
  demos/nx-next-monorepo-demo/workspace.json
Labels: type: chore, automerge

#1641 chore: standardise ODB terminology
  README.md
  cypress/integration/default/dynamic-routes.spec.ts
  demos/default/pages/getStaticProps/with-revalidate.js
  packages/runtime/src/templates/getHandler.ts
Labels: type: chore, automerge

#1634 fix: add missing data to middleware request object
  README.md
  jestSetup.js
  package-lock.json
  package.json
  packages/next/src/middleware/request.ts
  packages/next/test/request.spec.ts
  packages/runtime/src/helpers/edge.ts
  packages/runtime/src/templates/edge-shared/nextConfig.json
  packages/runtime/src/templates/edge/runtime.ts
Labels: type: bug, automerge

#1644 chore: disable critical css to avoid upstream bug
  demos/default/next.config.js
  test/index.js
Labels: type: bug, type: chore, automerge
