Repository opennextjs/opennextjs-netlify, pull requests merged in 2022-06, with the labels that each got.

#1370 chore: updated package lock in nx-monorepo demo and use legacy peer deps
  demos/nx-next-monorepo-demo/.npmrc
  demos/nx-next-monorepo-demo/package-lock.json
Labels: type: chore

#1358 feat: added better custom header support
  cypress/integration/default/headers.spec.ts
  demos/default/next.config.js
  plugin/src/helpers/config.ts
  plugin/src/index.ts
  test/index.js
Labels: type: feature, automerge

#1381 ci: build demos whenever plugin changes or cache cleared
  demos/base-path/netlify.toml
  demos/default/netlify.toml
  demos/middleware/netlify.toml
  demos/next-auth/netlify.toml
  demos/next-export/netlify.toml
  demos/next-i18next/netlify.toml
  demos/nx-next-monorepo-demo/netlify.toml
  demos/server-components/netlify.toml
  demos/static-root/netlify.toml
Labels: type: chore, automerge

#1382 fix: run edge middleware on data requests
  demos/middleware/middleware.ts
  demos/middleware/package.json
  demos/middleware/pages/index.js
  demos/middleware/pages/shows/static/[id].js
  package-lock.json
  plugin/src/templates/edge/runtime.ts
Labels: type: bug, automerge

#1376 chore: add codeowners and fixing pull request template
  .github/CODEOWNERS
  .github/pull_request_template.md
Labels: type: chore

#1392 fix: check for existence of experimental images
  package-lock.json
  plugin/src/index.ts
Labels: type: bug, automerge

#1395 chore(main): release plugin-nextjs 4.9.1
  .release-please-manifest.json
  plugin/CHANGELOG.md
  plugin/package.json
Labels: type: chore, automerge

#1398 chore: Revert "chore(deps): update dependency @netlify/build to ^27.1.3 (#1354)"
  package-lock.json
  package.json
  plugin/package.json
Labels: type: chore

#1353 chore: improve docs ISR with local files
  docs/isr.md
Labels: documentation, type: chore, automerge

#1406 chore: made custom ignore command more liberal
  demos/base-path/netlify.toml
  demos/canary/netlify.toml
  demos/default/netlify.toml
  demos/middleware/netlify.toml
  demos/next-auth/netlify.toml
  demos/next-export/netlify.toml
  demos/next-i18next/netlify.toml
  demos/nx-next-monorepo-demo/netlify.toml
  demos/server-components/netlify.toml
  demos/static-root/netlify.toml
Labels: type: chore

#1405 chore: added cypress/screenshots to git ignore
  .gitignore
Labels: type: chore

#1409 fix(deps): upgrade ipx
  package-lock.json
  plugin/package.json
Labels: type: bug, automerge

#1415 chore: add next to all demos
  demos/base-path/package.json
  demos/next-auth/package.json
  demos/next-export/package.json
  demos/static-root/package.json
  package-lock.json
Labels: type: chore, automerge

#1416 fix: handle missing manifest functions field
  plugin/src/helpers/edge.ts
Labels: type: bug, automerge

#1423 CODEOWNERS update 202206
  .github/CODEOWNERS
Labels: type: chore, automerge

#1427 chore: update next version
  cypress/integration/default/middleware.spec.ts
  demos/base-path/package.json
  demos/default/package.json
  demos/default/pages/getStaticProps/withFallbackAndMiddleware/[...slug].js
  demos/default/pages/getStaticProps/withFallbackAndMiddleware/[id].js
  demos/default/pages/getStaticProps/withFallbackAndMiddleware/_middleware.js
  demos/default/pages/index.js
  demos/default/pages/middle/_middleware.js
  demos/default/pages/middle/index.js
  demos/middleware/package.json
  demos/next-auth/package-lock.json
  demos/next-export/package.json
  demos/next-i18next/package-lock.json
  demos/next-i18next/package.json
  demos/nx-next-monorepo-demo/package-lock.json
  demos/nx-next-monorepo-demo/package.json
  demos/server-components/package.json
  demos/static-root/package.json
  package-lock.json
  package.json
  plugin/package.json
  test/__snapshots__/index.js.snap
  test/index.js
Labels: type: chore

#1425 feat: middleware warning
  README.md
  plugin/src/helpers/edge.ts
  plugin/src/index.ts
Labels: type: feature, automerge

#1435 fix: check for Middleware manifest & chain
  package-lock.json
  plugin/src/index.ts
Labels: type: bug, automerge

#1438 feat: use edge functions for content negotiation by default
  README.md
  demos/canary/next.config.js
  docs/isr.md
  plugin/src/helpers/edge.ts
  plugin/src/helpers/functions.ts
  plugin/src/index.ts
  plugin/src/templates/edge/ipx.ts
Labels: type: feature, automerge
