Repository opennextjs/opennextjs-netlify, pull requests merged in 2022-04, with the labels that each got.

#1289 chore: update the path for the import of type ImageConfigComplete
  demos/nx-next-monorepo-demo/package-lock.json
  demos/nx-next-monorepo-demo/package.json
  package-lock.json
  package.json
  src/helpers/functions.ts
Labels: type: chore, automerge

#1295 fix: :bug: include terser bundle into netlify functions
  cypress/integration/default/preview.spec.ts
  src/helpers/config.ts
  test/index.js
Labels: type: bug, automerge

#1303 ci: :sparkles: run tests on a nightly basis
  .github/workflows/test.yml
Labels: type: chore, automerge

#1304 refactor: move into npm workspace
  .github/workflows/release-please.yml
  .github/workflows/test.yml
  .nvmrc
  .prettierignore
  .release-please-manifest.json
  demos/base-path/netlify.toml
  demos/base-path/package.json
  demos/default/local-plugin/index.js
  demos/default/local-plugin/manifest.yml
  demos/default/local-plugin/package.json
  demos/default/netlify.toml
  demos/default/package.json
  demos/default/pages/env.tsx
  demos/default/tsconfig.json
  demos/next-export/local-plugin/index.js
  demos/next-export/local-plugin/manifest.yml
  demos/next-export/local-plugin/package-lock.json
  demos/next-export/local-plugin/package.json
  demos/next-export/netlify.toml
  demos/next-export/package.json
  demos/nx-next-monorepo-demo/local-plugin/index.js
  demos/plugin-wrapper/index.js
  demos/plugin-wrapper/manifest.yml
  demos/plugin-wrapper/package-lock.json
  demos/plugin-wrapper/package.json
  demos/static-root/netlify.toml
  demos/static-root/package.json
  package-lock.json
  package.json
  plugin/manifest.yml
  plugin/package.json
  plugin/src/constants.ts
  plugin/src/helpers/cache.ts
  plugin/src/helpers/config.ts
  plugin/src/helpers/files.ts
  plugin/src/helpers/functions.ts
  plugin/src/helpers/redirects.ts
  plugin/src/helpers/types.ts
  plugin/src/helpers/utils.ts
  plugin/src/helpers/verification.ts
  plugin/src/index.ts
  plugin/src/templates/getHandler.ts
  plugin/src/templates/getPageResolver.ts
  plugin/src/templates/handlerUtils.ts
  plugin/src/templates/ipx.ts
  plugin/tsconfig.json
  release-please-config.json
  test/index.js
  tsconfig.json
Labels: type: chore, automerge

#1314 ci: add missing dir to rsc demo
  .gitignore
  demos/server-components/lib/fetch-data.js
  demos/server-components/lib/get-comments.js
  demos/server-components/lib/get-item.js
  demos/server-components/lib/get-story-ids.js
  demos/server-components/lib/time-ago.js
  demos/server-components/lib/use-data.js
Labels: type: chore, automerge

#1315 fix: copy edge src file
  demos/middleware/netlify.toml
  demos/server-components/netlify.toml
  package-lock.json
  plugin/package.json
  plugin/src/helpers/edge.ts
Labels: type: bug, automerge

#1322 fix: pass x-middleware-rewrite header to client
  demos/middleware/pages/index.js
  demos/middleware/pages/shows/rewriteme/index.js
  plugin/src/templates/edge/utils.ts
Labels: type: bug, automerge

#1325 fix: handle absolute rewrite URLs
  demos/middleware/pages/index.js
  demos/middleware/pages/shows/rewrite-absolute/_middleware.ts
  demos/middleware/pages/shows/rewrite-absolute/index.js
  demos/middleware/pages/shows/rewrite-external/_middleware.ts
  demos/middleware/pages/shows/rewrite-external/index.js
  plugin/src/templates/edge/utils.ts
Labels: type: bug, automerge

#1309 feat: ✨ add out-of-the-box support for NextAuth.js
  demos/next-auth/.env.local.example
  demos/next-auth/.eslintrc
  demos/next-auth/.gitignore
  demos/next-auth/LICENSE
  demos/next-auth/README.md
  demos/next-auth/components/access-denied.tsx
  demos/next-auth/components/footer.module.css
  demos/next-auth/components/footer.tsx
  demos/next-auth/components/header.module.css
  demos/next-auth/components/header.tsx
  demos/next-auth/components/layout.tsx
  demos/next-auth/netlify.toml
  demos/next-auth/next-auth.d.ts
  demos/next-auth/next-env.d.ts
  demos/next-auth/package.json
  demos/next-auth/pages/_app.tsx
  demos/next-auth/pages/admin/_middleware.ts
  demos/next-auth/pages/admin/index.tsx
  demos/next-auth/pages/api-example.tsx
  demos/next-auth/pages/api/auth/[...nextauth].ts
  demos/next-auth/pages/api/examples/jwt.ts
  demos/next-auth/pages/api/examples/protected.ts
  demos/next-auth/pages/api/examples/session.ts
  demos/next-auth/pages/client.tsx
  demos/next-auth/pages/index.tsx
  demos/next-auth/pages/me/_middleware.ts
  demos/next-auth/pages/me/index.tsx
  demos/next-auth/pages/policy.tsx
  demos/next-auth/pages/protected.tsx
  demos/next-auth/pages/server.tsx
  demos/next-auth/pages/styles.css
  demos/next-auth/process.d.ts
  demos/next-auth/tsconfig.json
  plugin/src/helpers/config.ts
  plugin/src/helpers/utils.ts
  plugin/src/index.ts
  test/index.js
Labels: type: feature

#1328 fix: specify version of next-auth
  demos/next-auth/package.json
Labels: type: bug, type: chore, automerge

#1332 chore: rebuild default demo if any changes are made in repo
  demos/default/netlify.toml
Labels: type: chore, automerge
