Repository opennextjs/opennextjs-netlify, pull requests merged in 2022-11, with the labels that each got.

#1731 fix: only split extended routes to decrease build times
  packages/runtime/src/helpers/functions.ts
  packages/runtime/src/index.ts
  test/__snapshots__/index.js.snap
  test/index.js
Labels: type: bug

#1738 fix: resolve _app deps in API routes
  packages/runtime/src/helpers/functions.ts
  packages/runtime/src/templates/getPageResolver.ts
  test/__snapshots__/index.js.snap
  test/index.js
Labels: type: bug, automerge

#1745 fix: exclude swc by default, and don't exclude sharp if included
  packages/runtime/src/helpers/config.ts
  test/index.js
Labels: type: bug, automerge

#1756 fix: publish from subdirectory
  demos/nx-next-monorepo-demo/package-lock.json
  demos/nx-next-monorepo-demo/package.json
  package-lock.json
  packages/runtime/src/helpers/files.ts
  packages/runtime/src/helpers/redirects.ts
  packages/runtime/src/index.ts
  test/__snapshots__/index.js.snap
  test/index.js
Labels: type: bug, automerge

#1760 chore: add `pnpm` info to README
  README.md
Labels: type: chore, automerge

#1761 feat: add next debug logging
  packages/runtime/src/templates/getHandler.ts
Labels: type: feature, automerge

#1771 fix: revert publish from subdirectory
  packages/runtime/src/helpers/files.ts
  packages/runtime/src/helpers/redirects.ts
  packages/runtime/src/index.ts
  test/__snapshots__/index.js.snap
  test/index.js
Labels: type: bug, automerge

#1775 chore(deps): upgrade everything to latest Next and React
  demos/base-path/package.json
  demos/canary/package-lock.json
  demos/canary/package.json
  demos/custom-routes/package.json
  demos/default/package.json
  demos/middleware/package.json
  demos/next-auth/netlify.toml
  demos/next-auth/package.json
  demos/next-export/netlify.toml
  demos/next-export/package.json
  demos/next-i18next/package-lock.json
  demos/next-i18next/package.json
  demos/next-with-edge-functions/package.json
  demos/nx-next-monorepo-demo/package-lock.json
  demos/nx-next-monorepo-demo/package.json
  demos/plugin-wrapper/package.json
  demos/static-root/package.json
  demos/turborepo-next-monorepo-demo/package-lock.json
  demos/turborepo-next-monorepo-demo/package.json
  package-lock.json
  package.json
  packages/next/package.json
  packages/next/test/request.spec.ts
  packages/runtime/package.json
  packages/runtime/src/helpers/files.ts
  test/__snapshots__/index.js.snap
  test/analysis.spec.ts
Labels: type: chore, automerge

#1773 chore: add Next.js e2e tooling
  .github/workflows/e2e-next.yml
  demos/nx-next-monorepo-demo/package-lock.json
  package-lock.json
  package.json
  test/e2e/getserversideprops/app/next.config.js
  test/e2e/getserversideprops/app/pages/500.js
  test/e2e/getserversideprops/app/pages/_app.js
  test/e2e/getserversideprops/app/pages/another/index.js
  test/e2e/getserversideprops/app/pages/blog/[post]/[comment].js
  test/e2e/getserversideprops/app/pages/blog/[post]/index.js
  test/e2e/getserversideprops/app/pages/blog/index.js
  test/e2e/getserversideprops/app/pages/catchall/[...path].js
  test/e2e/getserversideprops/app/pages/custom-cache.js
  test/e2e/getserversideprops/app/pages/default-revalidate.js
  test/e2e/getserversideprops/app/pages/early-request-end.js
  test/e2e/getserversideprops/app/pages/enoent.js
  test/e2e/getserversideprops/app/pages/index.js
  test/e2e/getserversideprops/app/pages/invalid-keys.js
  test/e2e/getserversideprops/app/pages/non-json.js
  test/e2e/getserversideprops/app/pages/normal.js
  test/e2e/getserversideprops/app/pages/not-found/[slug].js
  test/e2e/getserversideprops/app/pages/not-found/index.js
  test/e2e/getserversideprops/app/pages/promise/index.js
  test/e2e/getserversideprops/app/pages/promise/mutate-res-no-streaming.js
  test/e2e/getserversideprops/app/pages/promise/mutate-res-props.js
  test/e2e/getserversideprops/app/pages/promise/mutate-res.js
  test/e2e/getserversideprops/app/pages/refresh.js
  test/e2e/getserversideprops/app/pages/slow/index.js
  test/e2e/getserversideprops/app/pages/something.js
  test/e2e/getserversideprops/app/pages/user/[user]/profile.js
  test/e2e/getserversideprops/app/world.txt
  test/e2e/getserversideprops/test/index.test.ts
  test/e2e/jest.config.js
  test/e2e/next-test-lib/README.md
  test/e2e/next-test-lib/amp-test-utils.js
  test/e2e/next-test-lib/browsers/base.ts
  test/e2e/next-test-lib/browsers/playwright.ts
  test/e2e/next-test-lib/browsers/selenium.ts
  test/e2e/next-test-lib/create-next-install.js
  test/e2e/next-test-lib/e2e-utils.ts
  test/e2e/next-test-lib/flat-map-polyfill.js
  test/e2e/next-test-lib/mocks-require-hook.js
  test/e2e/next-test-lib/next-modes/base.ts
  test/e2e/next-test-lib/next-modes/next-deploy.ts
  test/e2e/next-test-lib/next-test-utils.js
  test/e2e/next-test-lib/next-webdriver.ts
  test/e2e/next-test-lib/react-channel-require-hook.js
  test/e2e/tsconfig.json
  tsconfig.json
Labels: type: chore, automerge

#1780 fix: resolve all pages using nft
  demos/default/hello.txt
  demos/default/pages/getServerSideProps/file.js
  packages/runtime/src/helpers/functions.ts
  packages/runtime/src/index.ts
  packages/runtime/src/templates/getPageResolver.ts
  test/__snapshots__/index.js.snap
  test/index.js
Labels: type: bug, automerge

#1801 fix: better headers.getAll polyfill
  packages/runtime/src/helpers/edge.ts
Labels: type: bug, automerge

#1808 docs: added a link to the contributing guidelines in the PR template
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: documentation, type: chore

#1818 chore: fix eslint config
  .eslintignore
  .eslintrc.js
  jestSetup.js
  package-lock.json
  packages/runtime/src/templates/ipx.ts
Labels: type: chore, automerge

#1812 fix: fix Invalid URL error when using uppercase i18n url
  cypress/integration/middleware/enhanced.spec.ts
  demos/base-path/package.json
  demos/canary/package.json
  demos/custom-routes/package.json
  demos/default/package.json
  demos/middleware/next.config.js
  demos/next-auth/package.json
  demos/next-export/package.json
  demos/plugin-wrapper/package.json
  demos/static-root/package.json
  package-lock.json
  packages/next/package.json
  packages/next/src/middleware/request.ts
  packages/next/src/middleware/response.ts
  test/e2e/modified-tests/middleware-general/test/index.test.ts
Labels: type: bug, automerge
