Repository opennextjs/opennextjs-netlify, pull requests merged in 2022-02, with the labels that each got.

#1186 chore: auto submit plugin to Netlify plugin directory
  .github/workflows/release-please.yml
Labels: type: chore

#1171 fix: don't use ODB for routes that match middleware
  demos/default/local-plugin/package-lock.json
  demos/default/pages/getStaticProps/withFallbackAndMiddleware/[...slug].js
  demos/default/pages/getStaticProps/withFallbackAndMiddleware/[id].js
  demos/default/pages/getStaticProps/withFallbackAndMiddleware/_middleware.js
  demos/default/pages/index.js
  src/helpers/files.ts
  src/helpers/redirects.ts
  src/helpers/utils.ts
  test/__snapshots__/index.js.snap
Labels: type: bug, automerge

#1190 fix: correctly disable ISR disk flushing
  demos/default/pages/getStaticProps/withRevalidate/withFallbackBlocking/[id].js
  src/helpers/files.ts
  src/helpers/utils.ts
  test/__snapshots__/index.js.snap
  test/index.js
Labels: type: bug, automerge

#1172 chore: add e2e tests and demos
  .vscode/feat-test.code-snippets
  cypress/integration/default/css.spec.ts
  cypress/integration/default/env.spec.ts
  cypress/integration/default/layouts.spec.ts
  cypress/integration/default/middleware.spec.ts
  cypress/integration/default/script.spec.ts
  demos/default/.env.production
  demos/default/next-env.d.ts
  demos/default/next.config.js
  demos/default/pages/_app.tsx
  demos/default/pages/broken-image.tsx
  demos/default/pages/css/index.module.css
  demos/default/pages/css/index.tsx
  demos/default/pages/env.tsx
  demos/default/pages/font.tsx
  demos/default/pages/image.js
  demos/default/pages/layouts.tsx
  demos/default/pages/middle/_middleware.js
  demos/default/pages/script.tsx
  demos/default/style-sass-test/variables.module.scss
  demos/default/tsconfig.json
  package-lock.json
  package.json
  test/__snapshots__/index.js.snap
Labels: type: chore, automerge

#1213 fix: prepend basePath to static file URLs
  demos/base-path/.eslintrc
  demos/base-path/.gitignore
  demos/base-path/README.md
  demos/base-path/local-plugin/index.js
  demos/base-path/local-plugin/manifest.yml
  demos/base-path/local-plugin/package-lock.json
  demos/base-path/local-plugin/package.json
  demos/base-path/netlify.toml
  demos/base-path/next.config.js
  demos/base-path/pages/_app.js
  demos/base-path/pages/another.js
  demos/base-path/pages/api/hello.js
  demos/base-path/pages/dynamic/[dynamic]/index.js
  demos/base-path/pages/fallback/[dynamic]/index.js
  demos/base-path/pages/index.js
  demos/base-path/public/favicon.ico
  demos/base-path/styles/Home.module.css
  demos/base-path/styles/globals.css
  src/helpers/files.ts
  src/index.ts
Labels: type: bug, automerge
