Repository opennextjs/opennextjs-netlify, pull requests merged in 2022-12, with the labels that each got.

#1813 chore(docs): document additional way to manually install Next.js Runtime
  README.md
Labels: documentation, type: chore

#1778 fix: get source file for api routes in `src` subdirectory
  packages/runtime/src/helpers/files.ts
  packages/runtime/src/helpers/functions.ts
Labels: automerge

#1825 ci: increase test timeout
  test/e2e/jest.config.js
Labels: type: chore, automerge

#1823 fix: assign globals to `self`
  demos/middleware/middleware.ts
  demos/middleware/package.json
  package-lock.json
  packages/runtime/src/helpers/edge.ts
  packages/runtime/src/templates/edge/next-dev.js
Labels: type: bug, automerge

#1795 fix: use static 404 for non-prerendered dynamic routes without fallback
  cypress/integration/default/dynamic-routes.spec.ts
  packages/runtime/src/helpers/redirects.ts
  packages/runtime/src/helpers/utils.ts
  test/helpers/utils.spec.ts
Labels: type: bug, automerge

#1852 test: re-enable unit tests
  test/__snapshots__/index.spec.js.snap
  test/index.spec.js
Labels: type: chore, automerge

#1840 chore: update next to 13.0.7
  demos/base-path/package.json
  demos/canary/package.json
  demos/custom-routes/package.json
  demos/default/package.json
  demos/middleware/package.json
  demos/next-auth/package.json
  demos/next-export/package.json
  demos/next-with-edge-functions/package.json
  demos/static-root/package.json
  package-lock.json
  package.json
  packages/next/package.json
  packages/runtime/package.json
  test/e2e/modified-tests/middleware-general/test/index.test.ts
Labels: type: chore, automerge
