Repository opennextjs/opennextjs-netlify, pull requests merged in 2022-05, with the labels that each got.

#1336 feat: Include basePath property in NEXTAUTH_URL when present in config
  plugin/src/index.ts
  test/index.js
Labels: type: feature, automerge

#1339 chore: update RSC demo with new router syntax
  demos/middleware/package.json
  demos/server-components/netlify.toml
  demos/server-components/next.config.js
  demos/server-components/package.json
  demos/server-components/pages/item.server.js
  package-lock.json
Labels: type: chore, automerge

#1359 chore: change middleware demo to root level middleware file instead of nested
  demos/middleware/middleware.ts
  demos/middleware/package.json
  demos/middleware/pages/cookies/_middleware.ts
  demos/middleware/pages/shows/_middleware.ts
  demos/middleware/pages/shows/rewrite-absolute/_middleware.ts
  demos/middleware/pages/shows/rewrite-external/_middleware.ts
  demos/middleware/pages/shows/rewriteme/_middleware.ts
  package-lock.json
Labels: type: chore, automerge

#1360 fix: don't override user defined NEXTAUTH_URL
  package-lock.json
  package.json
  plugin/src/index.ts
  test/index.js
Labels: type: bug, automerge
