Repository opennextjs/opennextjs-netlify, pull requests merged in 2022-07, with the labels that each got.

#1434 chore: Remote patterns tests
  cypress/integration/default/images.spec.ts
  demos/default/next.config.js
  demos/default/pages/image.js
  test/index.js
Labels: type: chore

#1449 chore: add issues to project board automatically
  .github/workflows/add-to-project.yml
Labels: type: chore, automerge

#1457 fix: explicitly type image config in ipx edge function
  plugin/src/templates/edge/ipx.ts
Labels: type: bug, automerge

#1458 fix(demos): update edge runtime name
  demos/server-components/next.config.js
  demos/server-components/pages/csr.js
  demos/server-components/pages/rsc.server.js
  demos/server-components/pages/slow.server.js
Labels: type: bug, automerge

#1460 feat: get client IP from Context object rather than header
  plugin/src/templates/edge/runtime.ts
Labels: type: feature, automerge

#1462 fix: copy imageconfig into edge function dir
  plugin/src/helpers/edge.ts
  plugin/src/templates/edge/ipx.ts
  test/index.js
Labels: type: bug, automerge

#1463 fix: include css files in handler functions
  demos/default/next.config.js
  demos/default/package.json
  package-lock.json
  plugin/src/helpers/config.ts
  plugin/src/index.ts
  test/index.js
Labels: type: bug, automerge

#1466 ci: add custom routes demo
  demos/custom-routes/.eslintrc
  demos/custom-routes/netlify.toml
  demos/custom-routes/next-env.d.ts
  demos/custom-routes/next.config.js
  demos/custom-routes/package.json
  demos/custom-routes/pages/_sport/[slug]/index.js
  demos/custom-routes/pages/_sport/[slug]/test.js
  demos/custom-routes/pages/another/[id].js
  demos/custom-routes/pages/api/dynamic/[slug].js
  demos/custom-routes/pages/api/hello.js
  demos/custom-routes/pages/auto-export/[slug].js
  demos/custom-routes/pages/auto-export/another.js
  demos/custom-routes/pages/blog-catchall/[...slug].js
  demos/custom-routes/pages/blog/[post]/index.js
  demos/custom-routes/pages/docs/v2/more/now-for-github.js
  demos/custom-routes/pages/hello-again.js
  demos/custom-routes/pages/hello.js
  demos/custom-routes/pages/multi-rewrites.js
  demos/custom-routes/pages/nav.js
  demos/custom-routes/pages/overridden.js
  demos/custom-routes/pages/redirect-override.js
  demos/custom-routes/pages/with-params.js
  demos/custom-routes/public/blog/data.json
  demos/custom-routes/public/static/hello.txt
  demos/custom-routes/readme.md
  demos/custom-routes/tsconfig.json
  package-lock.json
  package.json
Labels: type: chore, automerge

#1467 fix: add better error messaging for builds
  package.json
  plugin/src/helpers/verification.ts
  test/helpers/verification.spec.ts
Labels: type: bug, automerge

#1447 feat: dx updates to default demo site
  .vscode/launch.json
  demos/default/package.json
  demos/default/pages/getStaticProps/[id].js
  demos/default/pages/getStaticProps/withFallback/[...slug].js
  demos/default/pages/getStaticProps/withFallback/[id].js
  demos/default/pages/getStaticProps/withFallbackBlocking/[id].js
  demos/default/pages/getStaticProps/withRevalidate/[id].js
  demos/default/pages/getStaticProps/withRevalidate/withFallback/[id].js
  demos/default/pages/getStaticProps/withRevalidate/withFallbackBlocking/[id].js
  demos/default/pages/index.js
  plugin/src/templates/getHandler.ts
  test/__snapshots__/index.js.snap
Labels: type: feature, automerge

#1480 fix: update patch syntax
  plugin/src/helpers/files.ts
Labels: type: bug, automerge

#1478 docs: update notes about running Middleware
  docs/middleware.md
Labels: documentation, automerge

#1479 feat: add enhanced middleware support
  .eslintignore
  .github/workflows/cypress-middleware.yml
  .gitignore
  .prettierignore
  cypress/config/middleware.json
  cypress/integration/middleware/enhanced.spec.ts
  cypress/integration/middleware/standard.spec.ts
  demos/middleware/middleware.ts
  demos/middleware/netlify.toml
  demos/middleware/next.config.js
  demos/middleware/package.json
  demos/middleware/pages/api/hello.js
  demos/middleware/pages/index.js
  demos/middleware/pages/static.js
  package-lock.json
  plugin/package.json
  plugin/src/middleware/html-rewriter.ts
  plugin/src/middleware/index.ts
  plugin/src/middleware/request.ts
  plugin/src/middleware/response.ts
  plugin/src/templates/edge/bundle.js
  plugin/src/templates/edge/ipx.ts
  plugin/src/templates/edge/runtime.ts
  plugin/src/templates/edge/utils.ts
  plugin/tsconfig.json
  tsconfig.json
Labels: type: feature, automerge
