Repository opennextjs/opennextjs-netlify, pull requests merged in 2022-10, with the labels that each got.

#1631 fix: correctly enable edge images
  package-lock.json
  packages/runtime/package.json
  packages/runtime/src/helpers/edge.ts
  packages/runtime/src/index.ts
  test/index.js
Labels: type: bug, automerge

#1653 feat: Add ability to disable ipx
  README.md
  demos/canary/pages/index.js
  demos/default/netlify.toml
  demos/default/next.config.js
  demos/default/package.json
  demos/default/pages/image.js
  packages/runtime/src/helpers/config.ts
  packages/runtime/src/helpers/edge.ts
  packages/runtime/src/helpers/functions.ts
  packages/runtime/src/helpers/utils.ts
  test/helpers/utils.spec.ts
  test/index.js
Labels: type: feature, automerge

#1656 chore: override semicolon lint rule
  .eslintrc.js
Labels: type: chore, automerge

#1657 test: fix test to match new minimum ODB TTL logging
  cypress/integration/default/dynamic-routes.spec.ts
Labels: type: chore, automerge

#1661 fix: validate next/image params
  package-lock.json
  packages/runtime/package.json
  packages/runtime/src/templates/edge/ipx.ts
  packages/runtime/src/templates/ipx.ts
Labels: type: bug, automerge

#1665 fix: remove localPrefix
  packages/runtime/src/templates/ipx.ts
Labels: type: bug, automerge

#1677 feat: cache redirects for 60 seconds if no ttl provided
  packages/runtime/src/templates/getHandler.ts
Labels: type: feature, automerge

#1669 feat: use display names for edge functions
  packages/runtime/src/helpers/edge.ts
Labels: type: feature, automerge

#1668 chore: rearrange plugin wrapper
  demos/base-path/netlify.toml
  demos/custom-routes/netlify.toml
  demos/default/netlify.toml
  demos/middleware/netlify.toml
  demos/next-auth/netlify.toml
  demos/next-export/netlify.toml
  demos/next-i18next/netlify.toml
  demos/next-with-edge-functions/netlify.toml
  demos/nx-next-monorepo-demo/netlify.toml
  demos/plugin-wrapper/README.md
  demos/plugin-wrapper/index.js
  demos/server-components/netlify.toml
  demos/static-root/netlify.toml
  demos/turborepo-next-monorepo-demo/netlify.toml
  demos/turborepo-next-monorepo-demo/packages/local-plugin/index.js
  demos/turborepo-next-monorepo-demo/packages/local-plugin/manifest.yml
  demos/turborepo-next-monorepo-demo/packages/local-plugin/package-lock.json
  demos/turborepo-next-monorepo-demo/packages/local-plugin/package.json
  package-lock.json
  packages/runtime/index.js
  packages/runtime/package.json
Labels: type: chore, automerge

#1682 fix: prevent Next from defining duplicate global property in edge functions
  cypress/integration/middleware/standard.spec.ts
  demos/middleware/pages/api/edge.ts
  packages/runtime/src/helpers/edge.ts
Labels: type: bug, automerge

#1691 fix: gracefully handle missing static analysis tools
  packages/runtime/src/helpers/analysis.ts
Labels: type: bug, automerge

#1694 chore: removed comment that is no longer necessary in the pull request template
  .github/pull_request_template.md
Labels: documentation, type: chore, automerge

#1697 fix: handle custom publish dir for api routes
  cypress/integration/nx/general.spec.ts
  demos/nx-next-monorepo-demo/apps/demo-monorepo/pages/api/hello.js
  demos/nx-next-monorepo-demo/libs/.gitkeep
  demos/nx-next-monorepo-demo/netlify.toml
  demos/nx-next-monorepo-demo/package-lock.json
  demos/nx-next-monorepo-demo/package.json
  demos/nx-next-monorepo-demo/plugin-wrapper/README.md
  demos/nx-next-monorepo-demo/plugin-wrapper/index.js
  demos/nx-next-monorepo-demo/plugin-wrapper/manifest.yml
  demos/nx-next-monorepo-demo/plugin-wrapper/package-lock.json
  demos/nx-next-monorepo-demo/plugin-wrapper/package.json
  demos/turborepo-next-monorepo-demo/apps/web/pages/api/hello.js
  demos/turborepo-next-monorepo-demo/package-lock.json
  package-lock.json
  packages/runtime/src/helpers/functions.ts
Labels: type: bug, automerge

#1693 fix: correctly handle matchers with lookaheads and i18n
  cypress/integration/middleware/enhanced.spec.ts
  cypress/integration/middleware/standard.spec.ts
  demos/middleware/middleware.ts
  demos/middleware/next.config.js
  package-lock.json
  packages/runtime/package.json
  packages/runtime/src/helpers/edge.ts
  packages/runtime/src/helpers/matchers.ts
  test/matchers.spec.ts
Labels: type: bug, automerge

#1711 chore: remove rsc demo
  demos/server-components/README.md
  demos/server-components/components/comment-form.js
  demos/server-components/components/comment.js
  demos/server-components/components/error-placeholder.client.js
  demos/server-components/components/footer.client.js
  demos/server-components/components/header.js
  demos/server-components/components/item.client.js
  demos/server-components/components/item.server.js
  demos/server-components/components/logo.js
  demos/server-components/components/meta.js
  demos/server-components/components/nav.js
  demos/server-components/components/page.client.js
  demos/server-components/components/server-info.server.js
  demos/server-components/components/skeletons.js
  demos/server-components/components/spinner.js
  demos/server-components/components/stories.client.js
  demos/server-components/components/story.client.js
  demos/server-components/lib/fetch-data.js
  demos/server-components/lib/get-comments.js
  demos/server-components/lib/get-item.js
  demos/server-components/lib/get-story-ids.js
  demos/server-components/lib/time-ago.js
  demos/server-components/lib/use-data.js
  demos/server-components/netlify.toml
  demos/server-components/next.config.js
  demos/server-components/package.json
  demos/server-components/pages/csr.js
  demos/server-components/pages/index.js
  demos/server-components/pages/item.server.js
  demos/server-components/pages/rsc.server.js
  demos/server-components/pages/slow.server.js
  demos/server-components/pages/ssr.js
Labels: type: chore, automerge

#1676 feat: add support for WebAssembly in edge runtime
  cypress/integration/default/wasm.spec.ts
  demos/default/next.config.js
  demos/default/package.json
  demos/default/pages/api/og.tsx
  package-lock.json
  packages/runtime/src/helpers/edge.ts
  packages/runtime/src/templates/edge-shared/utils.ts
  packages/runtime/src/templates/edge/bundle.js
  test/__snapshots__/index.js.snap
  test/index.js
Labels: type: feature, automerge

#1714 feat: support Next 13
  .github/workflows/test.yml
  .vscode/feat-test.code-snippets
  demos/base-path/package.json
  demos/custom-routes/package.json
  demos/default/package.json
  demos/default/pages/broken-image.tsx
  demos/default/pages/css/index.tsx
  demos/default/pages/deep/import.js
  demos/default/pages/font.tsx
  demos/default/pages/getServerSideProps/[id].js
  demos/default/pages/getServerSideProps/all/[[...slug]].js
  demos/default/pages/getServerSideProps/static.js
  demos/default/pages/getStaticProps/[id].js
  demos/default/pages/getStaticProps/env.js
  demos/default/pages/getStaticProps/static.js
  demos/default/pages/getStaticProps/with-revalidate-404.js
  demos/default/pages/getStaticProps/with-revalidate.js
  demos/default/pages/getStaticProps/withFallback/[...slug].js
  demos/default/pages/getStaticProps/withFallback/[id].js
  demos/default/pages/getStaticProps/withFallbackBlocking/[id].js
  demos/default/pages/getStaticProps/withRevalidate/[id].js
  demos/default/pages/getStaticProps/withRevalidate/withFallback/[id].js
  demos/default/pages/getStaticProps/withRevalidate/withFallbackBlocking/[id].js
  demos/default/pages/image.js
  demos/default/pages/index.js
  demos/default/pages/layouts.tsx
  demos/default/pages/previewTest.js
  demos/default/pages/shows/[...params].js
  demos/default/pages/shows/[id].js
  demos/default/pages/static.js
  demos/default/pages/static/[id].js
  demos/middleware/package.json
  demos/middleware/pages/shows/[id].js
  demos/middleware/pages/shows/index.js
  demos/middleware/pages/shows/static/[id].js
  demos/next-auth/components/footer.tsx
  demos/next-auth/components/header.tsx
  demos/next-auth/package.json
  demos/next-export/package.json
  demos/next-i18next/package-lock.json
  demos/next-i18next/package.json
  demos/next-i18next/pages/index.js
  demos/nx-next-monorepo-demo/package-lock.json
  demos/static-root/package.json
  demos/static-root/pages/index.js
  package-lock.json
  package.json
  packages/next/package.json
  packages/runtime/package.json
  packages/runtime/src/templates/edge/runtime.ts
Labels: type: chore, type: feature, automerge

#1680 fix: use process.env.URL when deploying to production
  demos/next-auth/package.json
  package-lock.json
  packages/runtime/src/index.ts
  test/index.js
Labels: type: bug, automerge

#1716 chore: update lockfile
  package-lock.json
Labels: type: chore, automerge

#1719 fix: follow redirects when downloading a file from the CDN
  package-lock.json
  packages/runtime/package.json
  packages/runtime/src/templates/handlerUtils.ts
Labels: type: bug, automerge

#1727 fix: disable minimal mode for API routes
  cypress/integration/default/api.spec.ts
  package-lock.json
  packages/runtime/src/templates/getApiHandler.ts
Labels: type: bug, automerge

#1730 fix: add cookies route to middleware config
  cypress/integration/middleware/standard.spec.ts
  demos/middleware/middleware.ts
Labels: type: bug

#1722 chore: replace next/legacy/image with next/image
  cypress/integration/default/images.spec.ts
  demos/default/next.config.js
  demos/default/pages/broken-image.tsx
  demos/default/pages/image.js
  demos/static-root/pages/index.js
  test/index.js
Labels: type: bug, type: chore, automerge
