Repository opennextjs/opennextjs-netlify, pull requests merged in 2023-07, with the labels that each got.

#2084 feat: Use `none` bundler for SSR Routes
  .eslintrc.js
  demos/canary/netlify.toml
  demos/default/netlify.toml
  demos/middleware/netlify.toml
  demos/nx-next-monorepo-demo/netlify.toml
  demos/static-root/netlify.toml
  packages/runtime/src/helpers/config.ts
  packages/runtime/src/helpers/flags.ts
  packages/runtime/src/helpers/functions.ts
  packages/runtime/src/index.ts
  packages/runtime/src/templates/getHandler.ts
Labels: type: feature, automerge

#2206 fix: use native path matching for prebundled react conditional
  packages/runtime/src/templates/server.ts
  test/templates/server.spec.ts
Labels: type: bug, automerge

#2224 chore: fix tests that rely on split route snapshots
  test/__snapshots__/index.spec.ts.snap
  test/index.spec.ts
Labels: type: chore, automerge
