Repository opennextjs/opennextjs-netlify, pull requests merged in 2023-10, with the labels that each got.

#2313 fix: improve support for new requireHooks update
  packages/runtime/src/helpers/config.ts
  packages/runtime/src/helpers/edge.ts
  packages/runtime/src/helpers/functions.ts
  packages/runtime/src/helpers/functionsMetaData.ts
  packages/runtime/src/helpers/utils.ts
  packages/runtime/src/index.ts
  packages/runtime/src/templates/getHandler.ts
  packages/runtime/src/templates/requireHooks.ts
  packages/runtime/src/templates/server.ts
  test/index.spec.ts
  test/templates/server.spec.ts
  test/test-utils.ts
Labels: type: bug, automerge

#2287 feat: add blob storage
  cypress/e2e/default/dynamic-routes.cy.ts
  package-lock.json
  packages/runtime/package.json
  packages/runtime/src/constants.ts
  packages/runtime/src/helpers/config.ts
  packages/runtime/src/helpers/files.ts
  packages/runtime/src/helpers/flags.ts
  packages/runtime/src/helpers/functions.ts
  packages/runtime/src/index.ts
  packages/runtime/src/templates/blobStorage.ts
  packages/runtime/src/templates/getHandler.ts
  packages/runtime/src/templates/handlerUtils.ts
  packages/runtime/src/templates/server.ts
  test/e2e/next-test-lib/fetch-polyfill.js
  test/e2e/next-test-lib/next-modes/next-deploy.ts
  test/index.spec.ts
  test/templates/handlerUtils.spec.ts
Labels: type: feature

#2341 fix: copy `vendor` over for local dev
  packages/runtime/package.json
  packages/runtime/patch-import-map.mjs
  packages/runtime/src/helpers/edge.ts
Labels: type: bug
