Repository opennextjs/opennextjs-netlify, pull requests merged in 2023-04, with the labels that each got.

#2026 test: skip tests to check for vary header containing 'RSC'
  cypress/integration/default/appdir.spec.ts
Labels: type: chore, automerge

#2018 fix: routes with null data routes can be filtered now
  packages/runtime/src/templates/edge-shared/rsc-data.ts
  test/rsc-data.spec.ts
Labels: type: bug, automerge

#2027 fix: support setting cookies from MiddlewareResponse
  cypress/integration/middleware/standard.spec.ts
  demos/middleware/middleware.ts
  demos/middleware/pages/cookies/middleware.js
  packages/next/src/middleware/response.ts
  packages/runtime/src/templates/edge-shared/utils.ts
Labels: type: bug, automerge

#1880 feat: use edge function layer for ipx
  packages/runtime/src/helpers/edge.ts
  packages/runtime/src/templates/edge/imageconfig.json
  packages/runtime/src/templates/edge/ipx.ts
Labels: type: feature

#2004 chore: delete e2e deploys in afterAll
  .github/workflows/e2e-appdir.yml
  .github/workflows/e2e-next.yml
  test/e2e/next-test-lib/next-modes/base.ts
  test/e2e/next-test-lib/next-modes/next-deploy.ts
Labels: type: chore

#2036 feat: support edge runtime key
  demos/default/pages/api/og.tsx
  demos/middleware/pages/api/edge.ts
  packages/runtime/src/helpers/analysis.ts
  packages/runtime/src/helpers/functions.ts
  test/e2e/app-dir/app-edge-global/next.config.js
  test/e2e/app-dir/app-edge/app/app-edge/page.tsx
  test/e2e/app-dir/app-edge/pages/pages-edge.tsx
  test/e2e/app-dir/app-middleware/pages/api/dump-headers-edge.js
  test/e2e/app-dir/app/app/(rootonly)/dashboard/hello/page.js
  test/e2e/app-dir/app/app/dashboard/page.js
  test/e2e/app-dir/app/app/edge-apis/cookies/page.js
  test/e2e/app-dir/app/app/slow-page-no-loading/page.js
  test/e2e/app-dir/app/app/slow-page-with-loading/page.js
  test/e2e/app-dir/app/pages/api/hello.js
  test/e2e/app-dir/next-font/app/page.js
  test/e2e/app-dir/next-image/app/page.js
  test/e2e/app-dir/rsc-basic/app/edge/dynamic/[id]/page.js
  test/e2e/app-dir/rsc-basic/app/edge/dynamic/page.js
  test/e2e/disabled-tests/edge-render-getserversideprops/app/pages/[id].js
  test/e2e/disabled-tests/edge-render-getserversideprops/app/pages/index.js
  test/e2e/disabled-tests/middleware-request-header-overrides/app/pages/api/dump-headers-edge.js
  test/e2e/modified-tests/edge-can-use-wasm-files/index.test.ts
  test/e2e/modified-tests/edge-compiler-can-import-blob-assets/app/pages/api/edge.js
  test/e2e/modified-tests/middleware-general/app/pages/api/edge-search-params.js
  test/e2e/modified-tests/skip-trailing-slash-redirect/app/pages/api/test-cookie-edge.js
  test/e2e/modified-tests/streaming-ssr/streaming-ssr/pages/api/user/[id].js
  test/e2e/modified-tests/streaming-ssr/streaming-ssr/pages/hello.js
  test/e2e/modified-tests/streaming-ssr/streaming-ssr/pages/index.js
  test/e2e/modified-tests/streaming-ssr/streaming-ssr/pages/multi-byte.js
  test/e2e/modified-tests/streaming-ssr/streaming-ssr/pages/router.js
  test/e2e/tests/edge-api-endpoints-can-receive-body/app/pages/api/edge.js
  test/e2e/tests/edge-api-endpoints-can-receive-body/app/pages/api/index.js
  test/e2e/tests/og-api/app/pages/api/og.js
  test/fixtures/analysis/background-edge.ts
  test/fixtures/analysis/scheduled-edge.ts
Labels: type: feature, automerge

#2041 fix: now data routes for dynamic routes filter even when null when creating the RSC data router
  packages/runtime/src/templates/edge-shared/rsc-data.ts
  test/rsc-data.spec.ts
Labels: type: bug, automerge

#2044 fix: ensure appDir routes with null dataRoutes are not added to edge manifest for rsc-data
  packages/runtime/src/helpers/edge.ts
  test/edge.spec.ts
Labels: type: bug, automerge

#2051 test: move e2e tests to a daily schedule
  .github/workflows/e2e-next.yml
Labels: type: chore

#2019 feat: add Generator to edge functions
  packages/runtime/src/helpers/edge.ts
  packages/runtime/src/helpers/functionsMetaData.ts
  test/edge.spec.ts
  test/functionsMetaData.spec.ts
  test/index.spec.js
Labels: type: feature, automerge

#2054 chore: test reorganization
  packages/runtime/src/templates/edge-shared/rsc-data.test.ts
  test/__snapshots__/index.spec.ts.snap
  test/helpers/analysis.spec.ts
  test/helpers/config.spec.ts
  test/helpers/edge.spec.ts
  test/helpers/files.spec.ts
  test/helpers/functions.spec.ts
  test/helpers/functionsMetaData.spec.ts
  test/helpers/matchers.spec.ts
  test/helpers/verification.spec.ts
  test/index.spec.ts
  test/templates/edge-shared/rsc-data.spec.ts
  test/templates/handlerUtils.spec.ts
  test/templates/server.spec.ts
  test/test-utils.ts
Labels: type: chore

#2060 fix: default to target: server, not serverless
  packages/runtime/src/helpers/files.ts
Labels: type: bug, automerge

#2030 fix: workaround netlify-cli not matching prod
  packages/runtime/src/templates/getHandler.ts
Labels: type: bug, automerge

#2069 chore: Optimize Cypress parallelization
  .github/workflows/cypress-canary.yml
  .github/workflows/cypress-demo-nx.yml
  .github/workflows/cypress-demo-static.yml
  .github/workflows/cypress-demo.yml
  .github/workflows/cypress-middleware.yml
Labels: type: chore

#2070 chore: Add `next` dep to renovate config
  renovate.json
Labels: type: chore, automerge

#2056 fix: update next to 13.3.0 & ensure compatibility
  cypress/e2e/default/appdir.cy.ts
  demos/base-path/package.json
  demos/canary/package.json
  demos/custom-routes/package.json
  demos/default/next-env.d.ts
  demos/default/package.json
  demos/default/tsconfig.json
  demos/middleware/package.json
  demos/next-auth/package.json
  demos/next-export/package.json
  demos/next-i18next/package.json
  demos/next-with-edge-functions/package.json
  demos/nx-next-monorepo-demo/package.json
  demos/static-root/package.json
  demos/turborepo-next-monorepo-demo/apps/docs/package.json
  demos/turborepo-next-monorepo-demo/apps/web/package.json
  demos/turborepo-next-monorepo-demo/package.json
  package-lock.json
  package.json
  packages/next/package.json
  packages/runtime/package.json
  packages/runtime/src/helpers/compiler.ts
  packages/runtime/src/helpers/files.ts
  packages/runtime/src/helpers/matchers.ts
  packages/runtime/src/templates/getPageResolver.ts
  test/__snapshots__/index.spec.ts.snap
  test/e2e/app-dir/app-edge.test.ts
  test/e2e/app-dir/app-edge/app/edge-apis/cookies/page.tsx
  test/e2e/app-dir/app-edge/app/edge/basic/page.tsx
  test/e2e/app-dir/app-edge/app/edge/layout.tsx
  test/e2e/app-dir/app-edge/app/edge/legacy/page.tsx
  test/e2e/app-dir/app-edge/pages/pages-edge.tsx
  test/e2e/app-dir/app-static.test.ts
  test/e2e/app-dir/head.test.ts
  test/e2e/app-dir/head/app/blog/[slug]/head.js
  test/e2e/app-dir/head/app/blog/[slug]/page.js
  test/e2e/app-dir/head/app/blog/about/page.js
  test/e2e/app-dir/head/app/blog/head.js
  test/e2e/app-dir/head/app/blog/layout.js
  test/e2e/app-dir/head/app/blog/page.js
  test/e2e/app-dir/head/app/head.js
  test/e2e/app-dir/head/app/layout.js
  test/e2e/app-dir/head/app/page.js
  test/e2e/app-dir/head/next.config.js
  test/e2e/app-dir/head/public/another.js
  test/e2e/app-dir/head/public/hello.js
  test/e2e/app-dir/head/public/hello1.js
  test/e2e/app-dir/head/public/hello2.js
  test/e2e/app-dir/head/public/hello3.js
  test/e2e/app-dir/index.test.ts
  test/e2e/app-dir/next-font.test.ts
  test/e2e/app-dir/rsc-basic.test.ts
  test/helpers/matchers.spec.ts
  test/helpers/verification.spec.ts
  test/index.spec.ts
  test/templates/server.spec.ts
Labels: type: bug, type: chore, automerge

#2057 fix: make large lambda warning message more informative
  packages/runtime/src/constants.ts
  packages/runtime/src/helpers/verification.ts
  test/helpers/verification.spec.ts
Labels: type: bug, automerge
