Repository opennextjs/opennextjs-netlify, pull requests merged in 2023-03, with the labels that each got.

#1952 chore: up test timeout
  test/e2e/jest.config.js
Labels: type: chore, automerge

#1946 chore: updated issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: type: chore

#1955 chore: disable edge-render tests
  test/e2e/disabled-tests/edge-render-getserversideprops/app/next.config.js
  test/e2e/disabled-tests/edge-render-getserversideprops/app/pages/[id].js
  test/e2e/disabled-tests/edge-render-getserversideprops/app/pages/index.js
  test/e2e/disabled-tests/edge-render-getserversideprops/index.test.ts
Labels: type: chore, automerge

#1970 feat: add multiple set-cookie headers in middleware
  package-lock.json
  packages/runtime/src/templates/edge-shared/utils.ts
  test/e2e/modified-tests/skip-trailing-slash-redirect/index.test.ts
Labels: type: feature, automerge

#1980 fix: remove fs access which isn't available in edge functions
  packages/runtime/src/templates/edge/next-dev.js
Labels: type: bug

#1984 fix: use the same id for importing and checking error
  packages/runtime/src/templates/edge/next-dev.js
Labels: type: bug, automerge

#1988 fix: make error message matching more generic
  packages/runtime/src/templates/edge/next-dev.js
Labels: type: bug, automerge

#1928 fix: updated redirect data urls
  packages/runtime/src/templates/edge-shared/utils.ts
  test/e2e/modified-tests/middleware-redirects/test/index.test.ts
Labels: type: bug, automerge

#2001 fix: use `IMAGE_FUNCTION_NAME` constant
  packages/runtime/src/helpers/config.ts
  packages/runtime/src/helpers/edge.ts
Labels: type: bug

#1999 feat: add generator meta data for framework generated Netlify Functions
  package-lock.json
  package.json
  packages/runtime/src/constants.ts
  packages/runtime/src/helpers/config.ts
  packages/runtime/src/helpers/functions.ts
  packages/runtime/src/helpers/functionsMetaData.ts
  test/functionsMetaData.spec.ts
Labels: type: bug, type: feature, automerge

#1993 test: added tests to check that the vary header contains 'RSC'
  cypress/integration/default/appdir.spec.ts
Labels: type: chore

#2009 fix: add fallback ID for scheduled test run
  .github/workflows/test.yml
Labels: type: bug
