Repository opennextjs/opennextjs-netlify, pull requests merged in 2023-02, with the labels that each got.

#1907 fix: add `AsyncLocalStorage` to `globalThis`
  demos/base-path/package.json
  demos/canary/package-lock.json
  demos/canary/package.json
  demos/custom-routes/package.json
  demos/default/app/app-edge/layout.tsx
  demos/default/app/app-edge/page.tsx
  demos/default/package.json
  demos/middleware/package.json
  demos/next-auth/package.json
  demos/next-export/package.json
  demos/next-with-edge-functions/package.json
  demos/static-root/package.json
  package-lock.json
  package.json
  packages/next/package.json
  packages/runtime/package.json
  packages/runtime/src/helpers/edge.ts
  test/__snapshots__/index.spec.js.snap
  test/e2e/tests/middleware-responses/test/index.test.ts
Labels: type: bug, automerge

#1916 refactor: extract edge runtime shims into separate file
  packages/runtime/src/helpers/edge.ts
  packages/runtime/src/templates/edge/shims.js
Labels: automerge

#1924 fix: change deprecated set-output github actions
  .github/workflows/pre-release.yml
Labels: type: bug

#1938 chore: fix typo in pull request template
  .github/pull_request_template.md
Labels: type: chore, automerge
