Repository opennextjs/opennextjs-netlify, pull requests merged in 2023-05, with the labels that each got.

#2076 chore: enable ESLint on `test` folder
  .eslintignore
  .eslintrc.js
  .prettierignore
  package-lock.json
  package.json
  packages/next/package.json
  packages/next/test/request.spec.ts
  test/fixtures/analysis/background.js.nft.json
  test/fixtures/not-static.json
  test/fixtures/page-extensions/custom/pages/api/custom.api.js
  test/fixtures/page-extensions/default/pages/api/default.js
  test/fixtures/serverless_next_config/next.config.js
  test/helpers/analysis.spec.ts
  test/helpers/config.spec.ts
  test/helpers/edge.spec.ts
  test/helpers/files.spec.ts
  test/helpers/functions.spec.ts
  test/helpers/functionsMetaData.spec.ts
  test/helpers/matchers.spec.ts
  test/helpers/utils.spec.ts
  test/helpers/verification.spec.ts
  test/index.spec.ts
  test/templates/handlerUtils.spec.ts
  test/templates/server.spec.ts
  test/test-utils.ts
Labels: type: chore

#2082 chore: fix broken image reference from npm package page
  packages/runtime/README.md
Labels: type: chore, automerge

#2050 fix: add shim for `require('node:buffer')`
  packages/runtime/src/templates/edge/shims.js
Labels: type: bug, automerge

#2059 fix: resolve next-server from next app directory and not from plugin
  .eslintignore
  .eslintrc.js
  .github/workflows/test-integration.yml
  package-lock.json
  package.json
  packages/runtime/src/helpers/analysis.ts
  packages/runtime/src/helpers/files.ts
  packages/runtime/src/helpers/functions.ts
  packages/runtime/src/helpers/types.ts
  packages/runtime/src/helpers/utils.ts
  packages/runtime/src/templates/getApiHandler.ts
  packages/runtime/src/templates/getHandler.ts
  packages/runtime/src/templates/handlerUtils.ts
  packages/runtime/src/templates/server.ts
  test/helpers/analysis.spec.ts
  test/index.spec.ts
  test/integration/fixtures/next-package-not-resolvable-in-base-dir/clear-node-modules-after-functions-bundling-plugin/index.js
  test/integration/fixtures/next-package-not-resolvable-in-base-dir/clear-node-modules-after-functions-bundling-plugin/manifest.yaml
  test/integration/fixtures/next-package-not-resolvable-in-base-dir/clear-node-modules-after-functions-bundling-plugin/package.json
  test/integration/fixtures/next-package-not-resolvable-in-base-dir/netlify.toml
  test/integration/fixtures/next-package-not-resolvable-in-base-dir/next-app/package.json
  test/integration/fixtures/next-package-not-resolvable-in-base-dir/next-app/pages/api/hello.js
  test/integration/fixtures/next-package-not-resolvable-in-base-dir/next-app/pages/index.js
  test/integration/jest.config.js
  test/integration/next-package-not-resolvable-in-base-dir.spec.ts
  test/templates/server.spec.ts
Labels: type: bug

#2087 chore: update github workflows
  .github/workflows/cypress-canary.yml
  .github/workflows/cypress-demo-nx.yml
  .github/workflows/cypress-demo-static.yml
  .github/workflows/cypress-demo.yml
  .github/workflows/cypress-middleware.yml
  .github/workflows/e2e-appdir.yml
  .github/workflows/e2e-next.yml
  .github/workflows/pre-release.yml
  .github/workflows/release-please.yml
  .github/workflows/test-deno.yml
  .github/workflows/test-integration.yml
  .github/workflows/test.yml
Labels: type: chore

#2074 Fix: Legacy fallback env var
  README.md
  demos/default/next.config.js
  packages/runtime/src/helpers/redirects.ts
  test/helpers/utils.spec.ts
Labels: type: bug

#2101 fix: support api routes at index of folder
  packages/runtime/src/helpers/files.ts
  test/fixtures/page-extensions/index/pages/api/index/index.js
  test/helpers/files.spec.ts
Labels: automerge

#2058 feat: split up API Routes + use .nft.json files to make builds fast
  .github/workflows/e2e-appdir.yml
  .github/workflows/e2e-next.yml
  .github/workflows/test-integration.yml
  .github/workflows/test.yml
  .gitignore
  cypress/e2e/default/revalidate.cy.ts
  demos/default/netlify.toml
  demos/middleware/netlify.toml
  demos/nx-next-monorepo-demo/netlify.toml
  demos/static-root/netlify.toml
  packages/runtime/src/helpers/config.ts
  packages/runtime/src/helpers/files.ts
  packages/runtime/src/helpers/flags.ts
  packages/runtime/src/helpers/functions.ts
  packages/runtime/src/helpers/pack.ts
  packages/runtime/src/helpers/redirects.ts
  packages/runtime/src/helpers/utils.ts
  packages/runtime/src/index.ts
  packages/runtime/src/templates/getApiHandler.ts
  packages/runtime/src/templates/getHandler.ts
  packages/runtime/src/templates/server.ts
  test/__snapshots__/index.spec.ts.snap
  test/helpers/functions.spec.ts
  test/helpers/pack.spec.ts
  test/index.spec.ts
  test/integration/next-package-not-resolvable-in-base-dir.spec.ts
  test/templates/server.spec.ts
Labels: type: feature

#1839 docs: add testing documentation
  README.md
Labels: automerge

#2113 fix: follow-up to split-api revalidate behaviour
  packages/runtime/src/helpers/functions.ts
  packages/runtime/src/index.ts
  packages/runtime/src/templates/getApiHandler.ts
  packages/runtime/src/templates/getHandler.ts
  packages/runtime/src/templates/server.ts
Labels: type: bug

#2114 Update CODEOWNERS (bulk-codeowners)
  .github/CODEOWNERS
Labels: automerge

#2115 chore: fix path for e2e tests
  .github/workflows/cypress-canary.yml
  .github/workflows/cypress-demo-nx.yml
  .github/workflows/cypress-demo-static.yml
  .github/workflows/cypress-demo.yml
  .github/workflows/cypress-middleware.yml
Labels: type: chore

#2116 fix: support named & default export for middleware in ntl dev
  packages/runtime/src/templates/edge-shared/utils.ts
  packages/runtime/src/templates/edge/next-dev.js
Labels: type: bug, automerge

#2121 fix: clientContext isn't available in background functions
  packages/runtime/src/templates/getApiHandler.ts
Labels: type: bug, automerge

#2124 fix: resolve follow-redirects from runtime package
  packages/runtime/src/helpers/functions.ts
Labels: type: bug

#2119 fix: checks when Next.js' implementation of ResponseCookies._headers is undefined now
  packages/runtime/src/templates/edge-shared/utils.ts
Labels: type: bug, automerge

#2104 fix: don't deploy metadata files to CDN
  packages/runtime/src/constants.ts
  packages/runtime/src/helpers/files.ts
  packages/runtime/src/helpers/redirects.ts
  packages/runtime/src/helpers/utils.ts
  packages/runtime/src/index.ts
  test/__snapshots__/index.spec.ts.snap
  test/e2e/next-test-lib/next-modes/next-deploy.ts
  test/helpers/utils.spec.ts
  test/index.spec.ts
Labels: type: bug, automerge

#2125 fix: guard split api routes behaviour by next version
  packages/runtime/src/helpers/config.ts
  packages/runtime/src/helpers/flags.ts
  packages/runtime/src/index.ts
  test/index.spec.ts
Labels: type: bug, automerge

#2133 fix: remove edge functions beta label
  packages/runtime/src/helpers/edge.ts
Labels: type: bug

#2138 fix: pass only first language to next-server to match platform redirects support
  cypress/e2e/default/i18n.cy.ts
  packages/runtime/src/templates/getHandler.ts
Labels: type: bug, automerge
