Repository opennextjs/opennextjs-netlify, pull requests merged in 2023-01, with the labels that each got.

#1863 chore: use api proxy for tv maze api
  demos/default/pages/api/shows/[...params].js
  demos/default/pages/api/shows/[id].js
  demos/default/pages/deep/import.js
  demos/default/pages/getServerSideProps/[id].js
  demos/default/pages/getServerSideProps/all/[[...slug]].js
  demos/default/pages/getServerSideProps/static.js
  demos/default/pages/getStaticProps/[id].js
  demos/default/pages/getStaticProps/static.js
  demos/default/pages/getStaticProps/with-revalidate.js
  demos/default/pages/getStaticProps/withFallback/[...slug].js
  demos/default/pages/getStaticProps/withFallback/[id].js
  demos/default/pages/getStaticProps/withFallbackBlocking/[id].js
  demos/default/pages/getStaticProps/withRevalidate/[id].js
  demos/default/pages/getStaticProps/withRevalidate/withFallback/[id].js
  demos/default/pages/getStaticProps/withRevalidate/withFallbackBlocking/[id].js
  demos/default/pages/index.js
  demos/default/pages/shows/[...params].js
  demos/default/pages/shows/[id].js
  demos/default/public/shows1.json
  demos/middleware/pages/shows/[id].js
  demos/middleware/pages/shows/static/[id].js
Labels: type: chore, automerge

#1865 chore: validate user input for tv maze urls
  demos/default/pages/api/shows/[...params].js
  demos/default/pages/api/shows/[id].js
  demos/default/pages/getServerSideProps/[id].js
  demos/default/pages/getServerSideProps/all/[[...slug]].js
  demos/default/pages/getStaticProps/[id].js
  demos/default/pages/getStaticProps/withFallback/[...slug].js
  demos/default/pages/getStaticProps/withFallback/[id].js
  demos/default/pages/getStaticProps/withFallbackBlocking/[id].js
  demos/default/pages/getStaticProps/withRevalidate/[id].js
  demos/default/pages/getStaticProps/withRevalidate/withFallback/[id].js
  demos/default/pages/getStaticProps/withRevalidate/withFallbackBlocking/[id].js
  demos/default/pages/shows/[...params].js
  demos/default/pages/shows/[id].js
  demos/middleware/pages/shows/[id].js
  demos/middleware/pages/shows/static/[id].js
  package-lock.json
Labels: type: chore, automerge

#1866 feat: add Next 13 request header mutation to middleware
  .github/workflows/test-deno.yml
  cypress/integration/middleware/enhanced.spec.ts
  cypress/integration/middleware/standard.spec.ts
  demos/middleware/middleware.ts
  package-lock.json
  package.json
  packages/runtime/src/templates/edge-shared/utils.test.ts
  packages/runtime/src/templates/edge-shared/utils.ts
Labels: type: feature, automerge

#1870 fix: merge Middleware and API route response cookies
  packages/runtime/src/templates/edge-shared/utils.ts
  test/e2e/modified-tests/skip-trailing-slash-redirect/index.test.ts
Labels: type: bug, automerge

#1855 fix: correctly handle ISR for appDir pages
  .github/workflows/e2e-appdir.yml
  .github/workflows/test.yml
  cypress/integration/default/appdir.spec.ts
  demos/default/.vscode/settings.json
  demos/default/app/blog/[author]/[slug]/page.tsx
  demos/default/app/blog/[author]/layout.js
  demos/default/app/blog/[author]/page.js
  demos/default/app/layout.js
  demos/default/next.config.js
  demos/default/pages/index.js
  demos/default/tsconfig.json
  package-lock.json
  package.json
  packages/runtime/src/helpers/edge.ts
  packages/runtime/src/helpers/files.ts
  packages/runtime/src/helpers/redirects.ts
  packages/runtime/src/helpers/utils.ts
  packages/runtime/src/templates/edge-shared/nextConfig.json
  packages/runtime/src/templates/edge-shared/prerender-manifest.json
  packages/runtime/src/templates/edge-shared/rsc-data.test.ts
  packages/runtime/src/templates/edge-shared/rsc-data.ts
  packages/runtime/src/templates/edge/rsc-data.ts
  packages/runtime/src/templates/getHandler.ts
  packages/runtime/src/templates/handlerUtils.ts
  test/__snapshots__/index.spec.js.snap
  test/e2e/app-dir/app-alias/package.json
  test/e2e/app-dir/app-static.test.ts
  test/e2e/disabled-tests/app-dir/app-alias.test.ts
  test/e2e/disabled-tests/app-dir/app-alias/next.config.js
  test/e2e/disabled-tests/app-dir/app-alias/src/app/button/page.tsx
  test/e2e/disabled-tests/app-dir/app-alias/src/app/layout.tsx
  test/e2e/disabled-tests/app-dir/app-alias/src/app/typing/page.tsx
  test/e2e/disabled-tests/app-dir/app-alias/tsconfig.json
  test/e2e/disabled-tests/app-dir/app-alias/ui/button.tsx
  test/e2e/disabled-tests/app-dir/app-alias/ui/style.module.css
  test/index.spec.js
Labels: type: bug, automerge

#1867 fix: correctly rewrite default locale ISR homepage to ODB handler
  demos/default/pages/index.js
  packages/runtime/src/helpers/redirects.ts
  test/__snapshots__/index.spec.js.snap
Labels: type: bug, automerge

#1809 fix: transform Regex named capture groups for Golang
  packages/runtime/src/helpers/edge.ts
  packages/runtime/src/helpers/matchers.ts
  test/e2e/tests/edge-render-getserversideprops/app/next.config.js
  test/e2e/tests/edge-render-getserversideprops/app/pages/[id].js
  test/e2e/tests/edge-render-getserversideprops/app/pages/index.js
  test/e2e/tests/edge-render-getserversideprops/index.test.ts
Labels: type: bug, automerge

#1894 test: re-disable edge-render-gssp test
  test/e2e/disabled-tests/edge-render-getserversideprops/app/next.config.js
  test/e2e/disabled-tests/edge-render-getserversideprops/app/pages/[id].js
  test/e2e/disabled-tests/edge-render-getserversideprops/app/pages/index.js
  test/e2e/disabled-tests/edge-render-getserversideprops/index.test.ts
Labels: type: chore, automerge

#1892 fix: match edge runtime pages with optional trailing slash
  packages/runtime/src/helpers/edge.ts
  packages/runtime/src/templates/edge-shared/utils.test.ts
  packages/runtime/src/templates/edge-shared/utils.ts
  packages/runtime/src/templates/edge/function-runtime.ts
  packages/runtime/src/templates/edge/middleware-runtime.ts
  test/e2e/modified-tests/streaming-ssr/index.test.ts
Labels: type: bug, automerge

#1888 fix: getMaxAge is not used in APIHandlers
  packages/runtime/src/templates/getApiHandler.ts
Labels: type: bug, automerge

#1895 docs: change _rewrites to _redirects in docs
  docs/redirects-rewrites.md
Labels: automerge

#1900 chore: update bug report template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: type: chore, automerge

#1893 fix: custom headers for root route when using i18n
  packages/runtime/src/helpers/config.ts
  packages/runtime/src/helpers/utils.ts
  test/index.spec.js
Labels: type: bug, automerge

#1903 fix: handle v1 edge function definition
  packages/runtime/src/helpers/edge.ts
  test/matchers.spec.ts
Labels: type: bug, automerge

#1896 fix: correctly match params in edge runtime
  demos/default/pages/edge/[id].js
  package-lock.json
  packages/runtime/src/helpers/edge.ts
  packages/runtime/src/templates/edge/bundle.js
  packages/runtime/src/templates/edge/function-runtime.ts
  test/__snapshots__/index.spec.js.snap
  test/e2e/app-dir/app-static.test.ts
  test/e2e/modified-tests/edge-render-getserversideprops/app/next.config.js
  test/e2e/modified-tests/edge-render-getserversideprops/app/pages/[id].js
  test/e2e/modified-tests/edge-render-getserversideprops/app/pages/index.js
  test/e2e/modified-tests/edge-render-getserversideprops/index.test.ts
  test/e2e/next-test-lib/next-test-utils.js
Labels: type: bug, automerge

#1905 fix: added support for "missing" matcher
  demos/middleware/middleware.ts
  demos/middleware/pages/matcher-cookie.js
  demos/middleware/pages/missing.js
  package-lock.json
  package.json
  packages/runtime/src/helpers/edge.ts
  packages/runtime/src/templates/edge-shared/next-utils.ts
  test/e2e/modified-tests/middleware-custom-matchers/test/index.test.ts
Labels: type: bug, automerge
