Repository opennextjs/opennextjs-netlify, pull requests merged in 2023-06, with the labels that each got.

#2117 fix: ensure next-server patches only run on Netlify
  packages/runtime/src/helpers/files.ts
Labels: type: bug, automerge, Ecosystem: Frameworks

#2155 feat: provide display name for split api routes
  packages/runtime/src/constants.ts
  packages/runtime/src/helpers/functions.ts
  test/__snapshots__/index.spec.ts.snap
  test/helpers/functions.spec.ts
  test/index.spec.ts
Labels: type: feature, automerge

#2154 fix: bundle dynamic API routes correctly with split-api-routes
  cypress/e2e/default/api.cy.ts
  packages/runtime/src/helpers/config.ts
Labels: type: bug, automerge

#2165 fix: new ISR cache handling to resolve regression in 13.4
  packages/runtime/src/helpers/dev.ts
  packages/runtime/src/helpers/files.ts
  packages/runtime/src/index.ts
  packages/runtime/src/templates/getHandler.ts
  packages/runtime/src/templates/server.ts
  test/helpers/files.spec.ts
Labels: type: bug

#2179 fix: optionally chain server functions when selecting react version
  packages/runtime/src/templates/server.ts
Labels: type: bug, automerge

#2159 fix: Return MiddlewareResponse obj for rewrite
  cypress/e2e/middleware/enhanced.cy.ts
  demos/middleware/middleware.ts
  demos/middleware/pages/request-rewrite.js
  demos/middleware/pages/static-rewrite.js
  packages/next/src/middleware/request.ts
  packages/next/src/middleware/response.ts
  test/e2e/next-test-lib/next-test-utils.js
Labels: type: bug, automerge

#2177 fix: preserve original path after middleware rewrite
  cypress/e2e/middleware/standard.cy.ts
  demos/middleware/middleware.ts
  demos/middleware/next.config.js
  demos/middleware/pages/locale-test.js
  packages/runtime/src/templates/edge-shared/utils.ts
  packages/runtime/src/templates/handlerUtils.ts
  packages/runtime/src/templates/server.ts
Labels: type: bug, automerge

#2189 fix: override headers within req.rewrite()
  cypress/e2e/middleware/enhanced.cy.ts
  demos/middleware/middleware.ts
  packages/next/src/middleware/response.ts
Labels: type: bug, automerge

#2188 fix: edge cases for custom react module resolution
  packages/runtime/src/templates/requireHooks.ts
  packages/runtime/src/templates/server.ts
Labels: type: bug, automerge
