Repository opennextjs/opennextjs-netlify, pull requests merged in 2025-01, with the labels that each got.

#2734 fix: adjust middleware json data rewrite to work with recent next@canary
  edge-runtime/lib/response.ts
  tests/e2e/edge-middleware.test.ts
  tests/fixtures/middleware-pages/next-env.d.ts
  tests/fixtures/middleware-pages/next.config.js
  tests/fixtures/middleware-pages/package.json
  tests/fixtures/middleware-pages/tsconfig.json
  tests/integration/edge-handler.test.ts
  tests/integration/page-router.test.ts
  tests/utils/create-e2e-fixture.ts
Labels: test all versions

#2737 chore(main): release 5.9.3
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2743 feat: add logging to understand impact of trailing slash 308s
  src/run/handlers/server.ts
  src/run/headers.ts
Labels: automerge

#2745 chore: add location header to trailing slash log
  src/run/headers.ts
Labels: automerge

#2741 chore(main): release 5.9.4
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2748 ci: increase number of shards when running Next.js repo e2e tests
  .github/workflows/test-e2e.yml
  tests/netlify-deploy.ts
Labels: run-e2e-tests
